### ISSUE TITLE
Datamodel: wat betekent "IsPublic"?

### ISSUE THREAD

**Issue by robhaans** [kadaster-labs/sensrnet-home#100]
In het huidige datamodel komt de entiteit "IsPublic" voor, als eigenschap van de datastream. Hiervoor is geen definitie gegeven. De vraag is wat hiermee bedoeld wordt. 

Als hiermee bedoeld wordt of de datastream publiek beschikbaar is, dan overlapt deze entiteit met de entiteit "IsOpendata". Als hiermee het gerefereerd wordt aan het publieke of private karakter van de datastream, dan is dit meer een eigenschap van de sensor of misschien zelfs van de eigenaar van de sensor of de verantwoordelijke van de datastream, niet van de datastream zelf in ieder geval. 

Wie kan hier duidelijkheid over geven?

**Comment by robhaans** [comment]
Sensor metadata is public of geheim -> isPublicSensor data is public of geheim -> isOpenDataEen link naar sensor data staat los van isOpenData, want het verwijzen naar de data heeft toegevoegde waarde voor meer dan alleen transparantie (bijv. voor andere overheden of bedrijven die wel toegang hebben, waar de data ook staat). In de presentatie aan de burger worden geen links getoond als de data niet open data is.

**Comment by robhaans** [comment]
In de werking van SensRNet moeten nog wel functionaliteiten gekoppeld worden aan deze data: vanuit het nodebeheer bepaalt dit veld of metadata in de publieke kaart getoond worden.

**Comment by marcvanandel** [comment]
Dit is besloten in FAB van 16 nov 2020 en moet nu 'refined' worden naar nieuwe issues voor de software ontwikkeling.
