### ISSUE TITLE
Datamodel - Aim

### ISSUE THREAD

**Issue by kad-bloemy** [kadaster-labs/sensrnet-home#101]
In het huidige datamodel is het kenmerk "Aim" opgenomen; een doel/grondslag, bedoeld om de vergunning of de verordening op te nemen die de sensor legitimeert. Dit is nu een kenmerk van Sensor. Vragen:
- Waarom is dit opgenomen? Wie wil dit weten, wie registreert dit?
- Is dit een kenmerk van Sensor of meer van Datastream of hebben beide misschien een dergelijke grondslag nodig?
We gaan er voorlopig vanuit dat het een kenmerk is van Datastream en hebben het "LegalGround" genoemd.

**Comment by robhaans** [comment]
Deze heb ik al geregistreerd: https://github.com/kadaster-labs/sensrnet-home/issues/95

**Comment by kad-bloemy** [comment]
Woeha, ik zie het. Ik probeer deze te verwijderen (en de andere dubbele)

**Comment by kad-bloemy** [comment]
Dubbel opgevoerd
