### ISSUE TITLE
Datamodel: "supplier" i.p.v. "manufacturer"

### ISSUE THREAD

**Issue by robhaans** [kadaster-labs/sensrnet-home#102]
In het huidige datamodel komt de entiteit "manufacturer" voor, als eigenschap van de sensor. Letterlijk betekent dit de fabrikant of producent van de sensor. Het is de vraag hoe relevant dit is om vast te leggen. Er zijn vaak meerdere fabrikanten betrokken bij een sensor. Wel is er meestal maar één leverancier: dit is de enige aanspreekbare partij voor de eigenaar/verantwoordelijke en daardoor veel relevanter dan fabrikant/producent. 

Overigens is het voor beide entiteiten de vraag hoe relevant het is om dit te delen in een sensorenregister. Heel logisch in een assetmanagement-omgeving, maar niet publiek-maatschappelijk interessant.

**Comment by kad-bloemy** [comment]
Ik zie nu beide eigenschappen in Sensor. Kan dit issue daarmee worden gesloten?

**Comment by kad-bloemy** [comment]
Zie #96. Kan deze worden gesloten?

**Comment by robhaans** [comment]
Ja, wat mij betreft wel. Moet in ieder geval in het datamodel.
