### ISSUE TITLE
Product visie in github documenteren

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#11]
Document (voorstel: `/docs/productvision.md`) om de visie voor het sensorenregister en de richting van uitwerking in SensRNet te beschrijven. Dit helpt om anderen te laten begrijpen wat we aan het doen zijn, ook voor het vervolg...

**Comment by marcvanandel** [comment]
Dit is / begint met de 'two-pager', denk ik ... maar dan in EN? Of in NL én in EN?

**Comment by grusma** [comment]
afhankelijk voor wie doen we het ;)?
de beste optie is in EN & NL, kan ook in PL ;)

**Comment by grusma** [comment]
[Op weg naar Nationale Sensorenregister_visie.docx](https://github.com/kadaster-labs/sensrnet-home/files/4651504/Op.weg.naar.Nationale.Sensorenregister_visie.docx)

**Comment by grusma** [comment]
[productvision.docx](https://github.com/kadaster-labs/sensrnet-home/files/4651518/productvision.docx)
