### ISSUE TITLE
Type Organisation uitwerken

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#110]
Is Organisation een overheid, een commercieel bedrijf of een burger? Hoe gaan we deze onderscheiden? (en hoe gaan deze zich authenticeren in een node?)

**Comment by kad-bloemy** [comment]
Willen we sensoren van particulieren registreren? Hangt ook van de doelstelling af: willen we een basisregistratie met allerlei eisen aan de input of willen we transparantie en een laagdrempelige registratie. In feite zijn het twee verschillende registraties. En misschien ook nog iets van signalering (bijv. van luchtkwaliteit, geluidsbelasting), zonder een officiële status. Hiervoor lijkt het RIVM als een platform te hebben.
Issues daarbij:
- verschil in kwaliteit tussen sensoren en dus de data;
- beheer van registratie door particulieren - je wil geen wildgroei.

**Comment by kad-bloemy** [comment]
De gemeente Amsterdam heeft een kaart ontwikkeld waarop de sensoren bekeken kunnen worden. https://maps.amsterdam.nl/privacy/
Sensoren vallen onder de informatieplicht van de eigenaren, zoals ook verwoord in de Algemene verordening persoonsgegevens (AVG). Sensoren van private eigenaren zijn niet in de kaart opgenomen om de volgende redenen:
-	In de AVG is het verwerken van sensordata voor huishoudelijk gebruik toegestaan. 
-	De locaties van private sensoren zijn privacygevoelig.
Een verdere overweging was bovendien dat het beheer van private sensoren niet handhaafbaar is. Amsterdam wilde klein beginnen om te kijken waar men tegenaan liep. De registratie van private sensoren is niet definitief uitgesloten, maar kan ooit als een facultatief register worden toegevoegd. Amsterdam wilde in eerste instantie afdwingbare registratie en dat kan niet met particulieren. De registratie is ook nadrukkelijk voor professioneel gebruik en van professionele eigenaren. Dit kunnen ook eenmanszaken zijn, maar dat komt niet veel voor. Het komt een verbod om sensoren te plaatsen zonder toestemming van de gemeente.
Amsterdam is momenteel bezig met de ontwikkeling van het meldingsformulier. Daarbij hebben ze overwogen om het type organisatie op te nemen, maar inmiddels hebben ze daarvan afgezien. De lijst met types leek oneindig te worden. Hetzelfde geldt voor het beroep van de eigenaar. Vooralsnog zijn sensoren voor openbare orde en vervolging uitgesloten van registratie.
In de viewer is een soort van drietrapsraket aangebracht voor de getoonde informatie:
-	Als je op een sensor klikt krijg je de informatie over de sensor te zien 
-	In deze informatie kan worden doorgeklikt naar specifieke informatie zoals een privacyverklaring. Dit houdt verband met de wettelijk verplichte informatie.
-	Uiteindelijk is het de bedoeling hier nog meer informatie of een link naar een website op te nemen

**Comment by marcvanandel** [comment]
De entiteit `Owner`, zoals deze eerst heette, duidt op de _rol_ van een organisatie en niet op wat het _is_ (_existance_). Daarom is `Organisation` al beter, want deze bestaat als zelfstandige entiteit met of zonder link naar sensoren en wat dan die link precies is.

De entiteit `Organisation` duidt eigenlijk op `Rechtspersoon` of misschien wel gewoon `Persoon`. In de eerste opzet worden alleen sensoren van overheden geregistreerd en daarom is deze (rechts)persoon altijd een organisatie. Als later sensoren van bedrijven toegevoegd gaan worden, dan is de (rechts)persoon nog steeds een organisatie. In geval de sensoren van burgers toegevoegd gaan worden, dan is 'organisatie' een beetje een raar woord. Dan zou (rechts)persoon beter zijn, waarbij een burger de eerste `Natuurlijke Persoon` zou zijn en de andere persona zijn allemaal `Niet-Natuurlijke Personen`. 

Misschien is het beter om hier naar gestandaardiseerde modellen te kijken in de basisregistraties of zo?

Deze entiteit staat trouwens los van de entiteit `User`, want dat is de daadwerkelijke persoon die als gebruiker inlogt in het systeem. In het geval van een organisatie is dat een persoon die deze organisatie vertegenwoordigd (in een bepaalde rol: admin, sensorenbeheerder). In geval van een burger is dit wel een 1-op-1 koppeling met de (rechts)persoon: 

`User [Marc]` - `Person [Marc]`

**Comment by marcvanandel** [comment]
Tja ... goed punt ... Hoewel eigenaar niet de lading dekt van alle verschillende rollen ... 🤔

**Comment by robhaans** [comment]
Ik heb voorgesteld de entiteit "organisatie" te vervangen door "rechtspersoon" ("LegalEntity"). Hieronder valt alles wat verantwoordelijkheid kan dragen, ook particulieren. 

Volgens mij is het niet van belang wat voor _type_ rechtspersoon het is. Het veld of de entiteit moet alleen zodanig zijn dat we geen potentiële gebruikers uitsluiten. De naam van de rechtspersoon en de contactgegevens zijn vooral noodzakelijk.

Of we wel of geen particulieren toelaten of particuliere organisaties, is vooral een vraagstuk voor de governance-groep.

**Comment by kad-bloemy** [comment]
In het datamodel zie ik nu bij Organisation: Id, Organisation code en Website. Waar verwijst Organisation code naar? Er moet wel een naam in, deze wordt getoond bij de sensor.  
Voorstel om Rechtspersoon in het datamodel op te nemen en vooralsnog op het scherm Organisatie te tonen, want de term Rechtspersoon kan bij burgers vragen oproepen. Vooralsnog registreren we alleen organisaties, geen particulieren.

**Comment by marcvanandel** [comment]
Dit kan eenvoudig in de vertaling van de labels gedaan worden

**Comment by kad-bloemy** [comment]
Besluiten, zoals besproken in FAB's van 28/1 en 10/2:
- Organisation blijft op het scherm, maar wordt Legal Entity in het datamodel. Nederlands: Organisatie resp. Rechtspersoon.
- Legal Entity krijgt de eigenschappen: Id, name, Website, Role (id, naam, website, rol).
- Type organisatie wordt niet vastgelegd voor dit MVP. 
- Particulieren kunnen geen sensor registreren.

**Comment by kad-bloemy** [comment]
In een sessie met Rob Haans gesproken over het datamodel en we hebben geconcludeerd dat er met name in het organisatie/rol/contactgegevens deel nogal wat wijzigingen nodig zijn. Rol en contactgegevens zouden dan moeten worden samengevoegd in een nieuwe entiteit. Overweging is dat elke rol zijn eigen contactgegevens heeft en dat bijvoorbeeld een legal-steward niet de contactgegevens van een device-owner mag wijzigen en andersom. Dit speelt bijvoorbeeld bij een gemeente, waar de rollen worden ingevuld door verschillende afdelingen of zelfs personen binnen een afdeling. Verder wil je dat er altijd én een device-owner én een sensor-owner én een legal-steward én een data-steward zijn geregistreerd. Vraag is of dit nog in het MVP moet worden gerealiseerd.

**Comment by marcvanandel** [comment]
Suggestie van Wim is om `LegalEntity` te beschouwen als een afdeling met (een bepaalde) verantwoordelijkheid. Daarmee is één gemeente als 'totaal eigenaar' te modelleren, maar ook afdelingen 'ieder voor zich'.

Wat ik graag zou willen bepleiten, is een eenvoudig model voor het MVP, dat later wellicht uitbreidbaar is. Ik denk namelijk dat we niet alle variaties nu al overzien en juist kunnen modelleren

**Comment by kad-bloemy** [comment]
Voor nu gaan we uit van slechts 2 rollen voor organisaties: Accountable (eindverantwoordelijke) en Responsible (beheerverantwoordelijke). De rollen van gegevensverantwoordelijke en metadata-verantwoordelijke zullen in een later stadium worden toegevoegd.

**Comment by marcvanandel** [comment]
In het datamodel zijn er twee specifieke implementaties van `LegalEntity` voorzien: `Organization` en `Citizen` aangezien daar wezenlijk verschil tussen is. Voor het MVP wordt alleen `Organization` gerealiseerd.

`Organization` staat voor zowel overheid, private partij, onderwijsinstelling, burgerinitiatief of enig andere vorm van organisatie. In hoeverre we kenmerken mee willen nemen voor het MVP, is nog punt van discussie. Is het mogelijk om een beperkt aantal zinnige en eindige kenmerken vast te stellen of is dit vooral discussie ... waarmee het niet voor het MVP meegenomen _kan_ worden
