### ISSUE TITLE
Registratie model uitwerken

### ISSUE THREAD

**Issue by grusma** [kadaster-labs/sensrnet-home#12]
Sensoren/meetapparaten

- (must) Waar staat de sensor/Domein: x,y,z (lat, lon)
_Location/Domain x,y,z (lat, lon, hight)_
- (must) Eigenaar/Domein: 
_Owner/Domain_
  - Naam contact persoon _Name contact person_
  - e-mail/telefoon contact persoon _e-mail/phone contact person_
  - Organisatie naam _Organization name_
  - Site met informatie over organisatie 
_Site with information about organization_
  - telefoon (klant contact center) =>let op AVG proof _phone (customer contact center) => please note AVG proof_ 
- (must) Is de sensordata openbaar? /Domein: ja; nee _Is the sensor data public? / Domain: yes; no_
- (must) Is de sensordata open data?/Domein: ja; nee _Is the sensor open data? / Domain: yes; no_
- (must) Is de data herbruikbaar? /Domein: ja; nee 
_Is the data reusable? / Domain: yes; no_
- (must) Vindplaats data/Domein: Link naar locatie met meer info (bijv. website met toelichting/contactgegevens) _Location of data / Domain: Link to location with more information (e.g. website with explanation / contact details)_
  - API
- (should) Object waar sensor aan vast zit/Domein: IMGeo ID, BGT++/IMGEO++ _Object where sensor is attached / Domain: IMGeo ID, BGT ++ / IMGEO ++_
- (should) Is de sensor actief /Domein: ja; nee (zoals in Eindhoven; niet actief – kleur grijs; actief kleur blauw) _Is the sensor active / Domain: yes; no_
- (would) Waarnemingsgebied/Domein: Geometrie vlak _Observation area / Domain: Geometry area_
- (would) Frequentie data verzameld wordt door de sensor _Frequency data is collected by the sensor_
**NEW (op basis van het gesprek op 15.05 met externe stakeholders Cathy, Rolf):
Categorieën apparaten: sensor; camera; beacon** _Device categories: sensor; camera; beacon_
 - (should) Link naar extra informatie (wat is beacon, actuator etc.)? _Link to additional information (what is beacon, actuator etc.)?_
  - (should) Link naar extra informatie (wat is beacon, actuator etc.)?
****NEW (op basis van het gesprek op 15.05 met externe stakeholders Cathy, Rolf):
**Weer, Natura&Milieu, Afval, Veiligheid, Mobiliteit, Bodem en ondergrond, Overig**** _Weather, Nature& Environment, Waste, Safety, Mobility, Soil and Underground, Other_
- Type sensor/meetapparaat /Domein: **NEW (eigenaar kan zelf bepalen aan welke thema welke meetapparaten vallen)** _Type of sensor / measuring device /can be different in every country_
  -Weerstation, Windmeter, Afvalcontainers, Fijnstofsensor, UV-sensor, Lichtcel, Milieuzone camera’s, Beveiligings-camera , Beweging ’s sensor, Brandmelder, Waterstand-meter, Microfoon/geluidmeter, Passantentellers, Radardetector, Flitser , GMS-sensor ; Detectielus¹ , Hoogtedetectie-apparaat, Navigatie beacon* (*dit is een opkomende ontwikkeling ivm Connected Autonomous Vehicles (CAV), deze zijn aanvullend nodig op satelliet navigatiesystemen in voertuigen. Dergelijke beacons zouden bijv gemonteerd kunnen worden in OVL-masten-info van gem. Utrecht)
 Debietmeter (IMGeo) _for example: Weather station, Wind gauge, Waste containers, Fine dust sensor, UV sensor, Light cell, Environmental zone cameras, Security camera, Motion sensor, Fire detector, Water level meter, Microphone / sound meter, Pedometer counters, Radar detector, Flash, GMS sensor; Detection loop¹, Height detection device, Navigation beacon * (* this is an emerging development related to Connected Autonomous Vehicles (CAV), these are additionally needed on satellite navigation systems in vehicles. Utrecht)Flow meter (IMGeo)_
  - (should) Link naar extra informatie (type sensoren) zoals Amsterdam _Link to additional information (type of sensors) such as Amsterdam_
- (must) Welke gegevens worden verzameld? Wat wordt gemeten/Domein: _Which data is collected? What is measured / Domain:_
 temperatuur/hitte; lucht drukte, gassen (CO, CO2…), zwerfvuil, fijnstof … het tellen van verschillende modaliteiten (drukte), trilling, geluid,…Riool, grondwater, conditie van infrastructuur (bijv. gasleidingen), zoutdetectie, droogte, oppervlaktewater kwaliteit, _temperature / heat; air pressure, gases (CO, CO2 ...), litter, particulate matter ... counting different modalities (pressure), vibration, noise, ... Sewer, groundwater, condition of infrastructure (eg gas pipes), salt detection, drought, surface water quality_
- Waarom? /Domein: vrije tekst _Why? the reason of the measurement / Domain: free text_
- kwaliteit quality/ Domain: free text_
- sensor fabrikant  sensor manufacturer / Domain: free text_

**Comment by marcvanandel** [comment]
- SensorThingAPI?
- Open Urban Platform?
- SmartM2M?

**Comment by kad-floriw** [comment]
Het lijkt mij mooi als tijdens het registreren van een sensor een sensor-type aangegeven kan worden (te kiezen uit een dropdown), waarbij dan door middel van een API call de bijbehorende data streams worden ingevuld (die je zelf nog kan aanpassen). Als je er voor kiest een (nog niet in de dropdown bestaand) nieuwe sensor-type aan te maken, kan je zelf de bijbehorende data streams ingeven. Dan kunnen we later ook opties maken om in de interface te filteren op sensor-type of sensor-data-stream.

**Comment by marcvanandel** [comment]
Yes! Goed idee, Wim. En dat kan heel prima in events worden gemodelleerd 💪 😃

**Comment by marcvanandel** [comment]
Event modeling in Miro aangemaakt: https://miro.com/app/board/o9J_ks90poQ=/

**Comment by grusma** [comment]
op basis van het gesprek op 15.05.2020 met externe stakeholders (Cathy, Rolf) en Mario:
1. Categorieën apparaten: sensor; camera; beacon (+mogelijkheid om een categorie zelf kunnen toe te voegen)
2. Thema's: Weer, Natura&Milieu, Afval, Veiligheid, Mobiliteit, Bodem en ondergrond, Overig (kan per gemeente verschillend)
3. Types meetapparaten: Weerstation (IMGeo), Windmeter (IMGeo), Afvalcontainers (bron Utrecht), Fijnstofsensor, UV-sensor, Lichtcel (IMGeo), Milieuzone camera’s (bron Utrecht), Beveiligings-camera (IMGeo), Beweging ’s sensor, Brandmelder, Waterstand-meter (IMGeo), Microfoon/geluidmeter, Passantentellers (bron Utrecht), Radardetector (IMGeo), Flitser (IMGeo), GMS-sensor (IMGeo); Detectielus¹ (IMGeo), Hoogtedetectie-apparaat (IMGeo), Navigatie beacon* 
4. informatie over Actuators kunnen in metadata gevonden worden
5.  Drager moet ook geregistreerd kunnen worden

Graag als metadata van de meetapparaten toevoegen:
- kwaliteit
- sensor fabrikant
- wat wordt gemeten
- doel, waarom wordt gemeten?

**Comment by grusma** [comment]
Wat betreft eigenaar/beheerder let op AVG en privacy gevoelig data; voorstel om een rol i.p.v naam toe te voegen

**Comment by marcvanandel** [comment]
> Wat betreft eigenaar/beheerder let op AVG en privacy gevoelig data; voorstel om een rol i.p.v naam toe te voegen

Of beide?

**Comment by marcvanandel** [comment]
PR #19 was een stukje van dit issue, maar daarmaa zou deze nog niet gesloten moeten worden ... 😉

**Comment by grusma** [comment]
> > Wat betreft eigenaar/beheerder let op AVG en privacy gevoelig data; voorstel om een rol i.p.v naam toe te voegen
> 
> Of beide?

ja, beide

**Comment by marcvanandel** [comment]
Johan tipt mij op het BGT informatie model: https://imgeo.geostandaarden.nl/def/imgeo-object/sensor
