### ISSUE TITLE
GitHub + VSCode online training organiseren

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#120]
Er is behoefte aan meer kennis en begrip rondom GitHub en VSCode, bijvoorbeeld voor het onderhouden en aandragen van wijzigingen in documentatie (zie [comments](https://github.com/kadaster-labs/sensrnet-home/issues/79#issuecomment-745996309))

Om meer input te krijgen zonder dit issue helemaal vol te laten lopen, ben ik een 'GitHub Discussion' begonnen: #121 

> NOTE GitHub Discussions is nieuwe functionaliteit in GitHub en is sinds half dec 2020 beschikbaar 😉

**Comment by marcvanandel** [comment]
Vanuit Code For NL, een stichting van developers binnen en buiten de overheid die voor een betere en open overheid zijn, wordt een sessie georganiseerd over ['hoe doe je een pull request?'](https://www.meetup.com/nl-NL/Code-For-NL/events/276025550/) 

Dat voorziet deels al in de behoefte in dit issue...

**Comment by robhaans** [comment]
Ik zag het al! Helaas heb ik al een overleg staan op dat tijdstip.. :(

**Comment by marcvanandel** [comment]
[labs.github.com](https://lab.github.com/) is ook heel duidelijk!

**Comment by marcvanandel** [comment]
Kunnen we dit issue sluiten of is hier nog erg veel behoefte aan?

**Comment by robhaans** [comment]
Kan gesloten worden

Van: Marc van Andel ***@***.***>
Verzonden: maandag 15 maart 2021 15:48
Aan: kadaster-labs/sensrnet-home ***@***.***>
CC: Rob Haans ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [kadaster-labs/sensrnet-home] GitHub + VSCode online training organiseren (#120)


Kunnen we dit issue sluiten of is hier nog erg veel behoefte aan?
