### ISSUE TITLE
Mijn sensoren lijst als 'edit tabel' kunnen gebruiken (Nice2Have)

### ISSUE THREAD

**Issue by rsleebos** [kadaster-labs/sensrnet-home#133]
- [x]  lijst met organisatie sensoren 'editable' maken zodat sensoren enkel of meerdere geselecteerd, gemuteerd, verwijderd of verplaatst kunnen worden.
- [ ]  lijst uitbreiden met alle invoervelden
- [x] ID van sensor ook zichtbaar maken

**Comment by marcvanandel** [comment]
Deze is klaar ... afgezien van 'alle velden'. Nieuwe wensen voor welke velden men zou willen zien, kunnen opgevoerd worden als nieuwe issues
