### ISSUE TITLE
Auto deploy (update) documentation in Home repo

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#137]
Als de documentation wordt bijgewerkt in de Home repo, dan zou automatisch publicatie daarvan moeten plaatsvinden op de `gh-pages` branch. Dit kan ingericht worden mbv de GitHub Actions (zijn die al toegestaan voor deze repo?)

**Comment by kad-busses** [comment]
GH Actions staan voor deze repo nog niet aan (Settings -> Actions), dat zou nog moeten.

We kunnen dan bijvoorbeeld de volgende actions gebruiken (werkt met MkDocs out-of-the-box):
https://github.com/marketplace/actions/github-pages-action

**Comment by marcvanandel** [comment]
Ah, nice. Dit vind ik wel leuk om uit te zoeken. Krijg ik ook nog 's wat ervaring met GH Actions 😉 Thnx for the heads up!

**Comment by marcvanandel** [comment]
Enable Actions aangevraagd bij Bert M.

**Comment by marcvanandel** [comment]
@kad-vossef , deze heb ik even tussendoor gedaan, dus nu worden wijzigingen in de `main` branch automagisch bijgewerkt in de gepubliceerde GitHub Pages site 😉 🎉
