### ISSUE TITLE
SensRNet @ Zuid-drecht.nl

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#142]
- publiceren op [ArtifactHub.io](https://artifacthub.io/) (á la [Conduction voorbeeld](https://github.com/ConductionNL/contactcatalogus/tree/master/api/helm))
  - 'value-schema.json moet je hebben'
  - Helm package publiceren
- default values moeten gevuld zijn
  - met namespace variabele
  - backend replica=0 als default?

**Comment by kad-busses** [comment]
- SensRNet staat nu op ArtifactHub: https://artifacthub.io/packages/search?org=sensrnet
  - value-schema.json is toegevoegd
  - Helm packages hadden we reeds gepubliceerd op GH Pages
- default waardes zijn gevuld. Moeten nog langs gelopen worden of die nog sense maken, misschien zijn ook niet alle variabelen nodig of ontbreken er nog een aantal
  - wat bedoel je met de namespace variabele?
  - backend replica staat nog op 1 nu. Liefste zou ik willen kijken waarom die connectie met ES niet goed gaat en dat eventueel de uitrol van de backend pas automatisch gebeurt als ES er klaar voor is. Niet heel gebruiksvriendelijk met deze tussenstap...
