### ISSUE TITLE
ADRs documenteren

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#146]
Documenting all architectural decisions made during the early development until the Minimum Viable Product need to created. This issue is for collecting all decisions to be documented.

**Comment by marcvanandel** [comment]
EN als default #92

**Comment by marcvanandel** [comment]
Welke issues zijn Closed en zouden hierin opgenomen moeten worden?

**Comment by marcvanandel** [comment]
Getting there ... als in: een start gemaakt met de opzet van het vastleggen van de ADRs op https://kadaster-labs.github.io/sensrnet-home/adr/ ;)

**Comment by kad-busses** [comment]
Nieuwe issues aangemaakt voor de nog openstaande bullets.
