### ISSUE TITLE
Code of conduct toevoegen

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#16]
Afkijken van [Standard for Public Code](https://standard.publiccode.net/CODE_OF_CONDUCT.html)?

**Comment by mario-schrijver** [comment]
Hi Marc,

Ik heb de voorbeeldcode gelezen. Ik ga er voor nu niet van uit dat er een risico is dat de deelnemers is onoirbaar gedrag vervallen. het betreft allen brave overheidsmedewerkers.

Mvrgr.,

Mario

**Comment by marcvanandel** [comment]
Nog een tip (via via) : https://www.contributor-covenant.org/nl/version/1/4/code-of-conduct/

**Comment by marcvanandel** [comment]
- `master` branch is protected
- peer review is required
- merge wordt gedaan door PR issuer

**Comment by marcvanandel** [comment]
@kad-vossef heb je hier nog enige voortgang op?

**Comment by kad-vossef** [comment]
Weinig, wel e.e.a. uitgezocht en ik kom morgen einde dag met de tekst

Van: Marc van Andel <notifications@github.com>
Verzonden: donderdag 4 juni 2020 09:57
Aan: kadaster-labs/sensrnet-home <sensrnet-home@noreply.github.com>
CC: Vossen, Frank <Frank.Vossen@kadaster.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [kadaster-labs/sensrnet-home] Code of conduct toevoegen (#16)


@kad-vossef<https://github.com/kad-vossef> heb je hier nog enige voortgang op?
