### ISSUE TITLE
Whitelist of mail address of public contacts details for privacy protection

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#162]
Indicated as risk in the privacy assessment #127 is that in the public contact details a private mail address can be entered. This should be prohibited.

Proposal is to whitelist the mail address field of (public) contact details.

Whitelist (_in wildcard, patterns where `*` stands for any character_):

- `*info*@*.*`
- `*sensor*@*.*`
- `*beheer*@*.*`
- `*privacy*@*.*`
- `*kcc*@*.*`
- `*service*@*.*`
- `*klant*@*.*`
- `*gemeente*@*.*`
- `*support*@*.*`
- `*help*@*.*`
- `*ondersteuning*@*.*`
- `*informatie*@*.*`.
- `*management*@*.*`
- `*team*@*.*`
- `*afdeling*@*.*`
- `*data*@*.*`

**Comment by robhaans** [comment]
gemeente@
beheerentoezichtopenbareruimte@
beheerteamovl@

**Comment by marcvanandel** [comment]
Als bovenstaande 'wildcards' zijn, patronen van de tekst die toegestaan zijn, dan worden de laatste twee al toegestaan. `gemeente@` heb ik toegevoegd aan het lijstje 👍

**Comment by CelineJansen** [comment]
Misschien nog:
*support*@*.*
*help*@*.*
*ondersteuning*@*.*
*informatie*@*.*
*management*@*.*
*team*@*.*
*afdeling*@*.*
*data*@*.*

**Comment by marcvanandel** [comment]
Melding voor niet-toegestane emailadressen met daarin instructie hoe deze toe te voegen (GitHub issue? mail naar sensrnet@kadaster.nl?)

**Comment by kad-busses** [comment]
Geïmplementeerd in https://github.com/kadaster-labs/sensrnet-registry-frontend/pull/153 en https://github.com/kadaster-labs/sensrnet-registry-backend/pull/106
