### ISSUE TITLE
Contribution guide toevoegen

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#17]
Afkijken van [Standard for Public Code](https://standard.publiccode.net/CONTRIBUTING.html)?

**Comment by mario-schrijver** [comment]
Mijn voorstel is de Github richtlijnen en flow op dit vlak  te volgen.

**Comment by marcvanandel** [comment]
Wat zijn de 'github richtlijnen' dan? Volgens mij is het gebruikelijk om zoiets van tevoren op te stellen en dat is per project / repo verschillend. Lijkt me zinnig om daar nu al iets van op te stellen zonder dat super uitgebreid te doen. Maar uiteindelijk zijn we gericht op samenwerking, dus is het wel fijn dat dat er vanaf straalt en dat we daar 'klaar' voor zijn, niet?
