### ISSUE TITLE
Waardelijsten publiceren bij de definities

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#175]

**Comment by kad-bloemy** [comment]
Links naar waardelijsten toegevoegd in Definitions. Het zijn links naar de Excelbestanden in de directory. Als je erop clickt moet je het bestand nog downloaden. Meteen de linkjes naar de issues gerepareerd, werken ook weer. Ik kijk even of er nog meer issues moeten worden opgenomen bij de definitions.

**Comment by marcvanandel** [comment]
@CelineJansen heeft in de zip file een Excel zitten als template én als invoerhulp ... met ook toelichtingen bij velden. In sommige gevallen is dat 1-op-1 de Definitions, maar soms zijn dat uitgebreidere beschrijvingen. @kad-bloemy , kun je die meenemen en toevoegen / bijwerken in de Definitions? (in het kader van dat je die toch onder handen hebt 😉 )

**Comment by CelineJansen** [comment]
[TemplateOpvoerAPI.xlsx](https://github.com/kadaster-labs/sensrnet-home/files/8030823/TemplateOpvoerAPI.xlsx)
Hier nog rechtstreeks de file. Wie weet heb je er wat aan.

**Comment by marcvanandel** [comment]
Definitions zijn opnieuw en anders gepubliceerd. Waardelijsten (Value lists) zijn daarin een apart kopje waar ook in de definities naar wordt verwezen. De nieuwe pagina is nu ook beter terug te vinden in het menu en gepubliceerd op https://kadaster-labs.github.io/sensrnet-home/Definitions/
