### ISSUE TITLE
lat lon als benaming voor coordinaten

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#177]
- [x] in frontend
- [x] in central viewer
- [ ]  beter documenteren waarom we gekozen hebben voor lat lon (ipv RD of iets anders)

**Comment by kad-busses** [comment]
`x` `y` in RD kwam inderdaad in de interface voor bij de muislocatie op de kaart
![image](https://user-images.githubusercontent.com/56066664/119476823-b5323f80-bd4e-11eb-93ff-3be4cb1f4179.png)

Dit was nog een generieke-geo-componenten feature, die niet opnieuw is toegevoegd met het migreren naar standaard Open Layers. In de laatste versie van de frontend/viewer is er daardoor geen verwijzing naar het stelsel waarin er technisch opgeslagen wordt.

Het documenteren van de keuze is ondergebracht onder https://github.com/kadaster-labs/sensrnet-home/issues/182
