### ISSUE TITLE
Load / Stress test backend-sync-multichain-viewer

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#189]
Load / Stress testing MultiChain node + netwerk om te onderzoeken hoe groot de noodzaak is om MultiChain high available te maken
- white paper over schrijven?
- 3 k8s clusters met backend-sync-multichain
- elk cluster een csv file via API van de backend met 100.000 sensors toevoegen?
- central viewer meenemen tbv visualisatie + performance van de viewer

**Comment by marcvanandel** [comment]
Planned for 22nd of June

**Comment by marcvanandel** [comment]
That was interesting. The result of many device on the map in the Central Viewer is ... overwelming 😄 

![image](https://user-images.githubusercontent.com/2315396/123041776-19036300-d3f6-11eb-92d7-775ae40fcac7.png)

- setting up the test environments with the [Haven terraforms](https://haven.commonground.nl/docs/aan-de-slag/azure) (we used v7 instead of the more complex v8) was very easy; great way to set up a cluster !!
- deploying all components was ... not as easy as expected. Deployment of single components is straightforward ... but the collection running together and integrated and connected properly to the internet is a bit harder. Still, within 6 hours we set up 3 Registry Node clusters and a Publishing Node all connected! Although it didn't feel as quick as expected this is still quite a impressive result 😊 
- setting up the MultiChain node with a private key didn't work. We've fixed this along the way:
  - the private key could not be provided in the helm-chart -> fixed with https://github.com/kadaster-labs/sensrnet-helm-charts/pull/17
  - generation of a private key depends  on the chain settings. The current script contains the production chain settings. For now we solved this by temporarily updating the constants in the script with our test net settings -> worked like a charm!
-  the Central Viewer Geoserver component was not released yet with the bundling of devices. So first view with many sensors (e.g. 10k) was very ugly and massive. After releasing the grouped layer in Geoserver the Central Viewer was a lot more acceptable as the image above shows. Still ... could be improved 😉 
- after scaling up the load on the backend we finally found an interesting failure in the system (with 60k sensors pushed to the backend with 1000 concurrent threads so at a really high load !! 😳 ) The EventstoreDB containers were not as stable as expected and this made the backend crash and be restarted by the Kubernetes platform. This is something we need to look into, especially the EventstoreDB. We've encountered issues earlier on the project but these are very hard to solve. So first we have to upgrade to the latest (LTS) version and see what has been solved in the product before looking into it ourselves -> https://github.com/kadaster-labs/sensrnet-registry-backend/issues/116

All in all we did have fun and gained a lot of experience ... and for short term there are no real issues with the performance of the system 💪 . Probably for the mid long term we need to figure out the issues with the EventstoreDB and maybe some improvements on the visual part in the Central Viewer?

**Comment by marcvanandel** [comment]
4 digits is possible too!

![image](https://user-images.githubusercontent.com/2315396/123083941-e458d100-d420-11eb-8993-89fd6a2b23db.png)

**Comment by marcvanandel** [comment]
Nog 's uit te zoeken / te verbeteren punten:

- alerting bij containers met `CrashLoopBackoff`
- MultiChain Explorer uit `multichain-node` halen, zeker als main process
- MultiChain Persistent Storage Claim ophogen 1 Gi -> 15 Gi?
- MultiChain gedrag als viewer node down is / gaat (deze is nu als enige admin bij gebrek aan andere nodes)
- Memory usage van Geoserver (voor Publishing Node)

**Comment by kad-busses** [comment]
Om nog een beetje in te gaan op je opmerking:

> deploying all components was ... not as easy as expected

Dit is wel een belangrijke, gezien iedereen die met SensRNet mee wilt doen (of de implementerende beheerder) hiermee in aanraking komt. De struggles kwamen volgens mij doordat nog niet alle componenten volledig bijgewerkt en gereleased waren, en daarmee de Helm Charts ook nog niet up-to-date. Ook waren we tijd kwijt aan Dex (zowel endpoints als programmatisch ophalen van een token) en de Ingresses, welke beiden nog beschreven werden door verouderde documentatie.

Verdere punten zouden dan daarom kunnen zijn:
- Documentatie bijwerken met juiste Helm commando's (voor Dex endpoints en Ingresses)
- Duidelijkere logging voor sneller probleemopsporing (vooral MultiChain niet altijd makkelijk te doorgronden)
- Ons interne ontwikkelproces evalueren of het wel makkelijk genoeg is de releases up-to-date te houden
- Testscript inchecken (als dat nog niet gedaan was)
- Testscript met automatische authorisatie in Dex
- Testscript in Docker zodat we eenvoudig(er) de backend kunnen bestoken vanaf het cluster zelf, voor alle testnodes tegelijk

De laatste punten over het testen zijn zowel handig voor een eventuele volgende testronde, als testing tools voor overige partijen die met onze stack aan de slag willen.
