### ISSUE TITLE
Eenheden / unit of measurement

### ISSUE THREAD

**Issue by CelineJansen** [kadaster-labs/sensrnet-home#196]
Hierbij een voorzet voor een waardelijst met eenheden tbv het attribuut "unit of measurement".
Als er nog opvallende dingen missen, vul dit dan vooral aan.
[VoorzetEenheden.xlsx](https://github.com/kadaster-labs/sensrnet-home/files/6661352/VoorzetEenheden.xlsx)

**Comment by kad-bloemy** [comment]
Ik zie nu pas dat jij er ook bent ingedoken en zelfs al een voorzet hebt! 
Ik had al comment geplaatste bij issue #176, maar ontdek net dat hier een wet aan gewijd is: https://wetten.overheid.nl/BWBR0020422/2020-06-13, waarin niet alleen de grootheden, maar ook de afgeleiden zijn opgenomen zoals milli, centi, deci etc.. 
In plaats van de Unified Code for Unit of Measure (UCUM) lijkt de lijst met SI-eenheden dus meer geëigend; zie hiervoor https://nl.wikipedia.org/wiki/SI-stelsel.

**Comment by CelineJansen** [comment]
Status 22-09-2021 (https://github.com/kadaster-labs/sensrnet-home/issues/176): we gaan een doorzoekbare keuzelijst met UCUM velden proberen (misschien is deze te lang, dat moet praktijkgebruik dan uitwijzen).

**Comment by kad-bloemy** [comment]
Zie verwijzing in #193

**Comment by kad-bloemy** [comment]
Ik ben er nog een keer ingedoken en het lijkt me ondoenlijk om een zinvolle selectie te maken. Je zou bij elke sensor moeten kijken wat ie meet en dan nog zijn er teveel variabelen. Iets simpels als snelheid: wordt dat m/min, m/sec, km/uur, hm/min etc. etc. Klik voor de lol eens op een maateenheid in https://www.hobbyprojects.com/dictionary_of_units.html en zie de alternatieven. Het meest praktische is toch om dit een vrij invoerveld te maken, zodat er in ieder geval een indicatie is van wat de meeteenheid is. Degenen die hiermee iets willen, kunnen dan contact opnemen met de verantwoordelijken. De lijst van Celine lijkt mij veel te beperkt voor alle mogelijke sensoren en wat moet er dan ingevuld worden als iets niet op de lijst voorkomt?

**Comment by kad-bloemy** [comment]
Je kunt voor UCUM units of measurements API's downloaden met/zonder libraries, maar dan moet je wel gebruikers hebben die precies weten wat ze willen. Ik betwijfel of dat zo zal zijn en dan creëer je schijnnauwkeurigheid.

**Comment by marcvanandel** [comment]
Check. Dan stel ik voor dat het in de API, backend en events in ieder geval een vrij veld is. In de frontend zouden we de gebruiker misschien nog kunnen ondersteunen met suggesties? Of een keuze tussen vrij veld en precieze notaties? (zie ook #143 opties)

**Comment by kad-bloemy** [comment]
Daar is misschien wel iets voor te bedenken, bijvoorbeeld twee velden, waarvan eentje voor een maat en een tweede voor de "per" eenheid.
