### ISSUE TITLE
Hardening Registry Node components

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#197]
For the Registry Node components hardening is a necessity.

- [x] Frontend -> [nginx hardening](https://kubernetes.github.io/ingress-nginx/deploy/hardening-guide/) (esp. 5.3) and [this blog](https://www.acunetix.com/blog/web-security-zone/hardening-nginx/)
- [x] Backend -> [NestJS with Helmet](https://docs.nestjs.com/security/helmet)

(other APIs are all internal and not exposed to the 'evil' outside world)

**Comment by marcvanandel** [comment]
Working on the backend and added the helmet lib. Response headers changing from:

![image](https://user-images.githubusercontent.com/2315396/122530160-7e360d80-d01e-11eb-9ae2-8cccbebdd846.png)

To:

![image](https://user-images.githubusercontent.com/2315396/122523742-a4a47a80-d017-11eb-8567-828b66457773.png)

**Comment by marcvanandel** [comment]
Backend fixed with https://github.com/kadaster-labs/sensrnet-registry-backend/pull/115

**Comment by marcvanandel** [comment]
And hardened the frontend with https://github.com/kadaster-labs/sensrnet-registry-frontend/pull/168

**Comment by marcvanandel** [comment]
Plus https://github.com/kadaster-labs/sensrnet-central-viewer/pull/32

**Comment by banaan666** [comment]
You might want to remove the "; includeSubdomains" part from _strict-transport-security_ header since any subdomain if it will ever exist could be handled by a different container with different requirements for any reason. This setup will force HTTPS on any subdomain for a long time. Which could be a pain when you are testing for example.

**Comment by marcvanandel** [comment]
Check. Deze header hoort bij HSTS en kan niet vanuit de applicatie worden ingesteld. Dat moet op het entrypoint / reverse proxy gebeuren. Dit moeten we in onze documentatie opnemen.

**Comment by rjzondervan** [comment]
Reeds op verzoek van Wim geregeld op de nginx-ingress

**Comment by marcvanandel** [comment]
Yes! Opgeleverd.
