### ISSUE TITLE
Sensor eigenaar kan zichzelf registreren als eigenaar

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#2]
Een eigenaar kan een particulier zijn of een organisatie. De velden zijn anders (zie SensorPilot).

Een eigenaar kan zich registreren en zijn gegevens (centraal?) beheren:
- Sensor eigenaar is een aparte entiteit (los van de sensoren die hij registreert) -> wat is het data model? Wat is mogelijk private data? Wat is mogelijk publieke data? Wat zijn verplichte velden? Minimaal contactgegevens (één van email of telefoon?) ivm calamiteiten, beheer, ordebewaking, etc ...
  - Wat zijn de eisen voor een particulier? Vergunningsverplichting? Koppeling met formele identiteit (paspoort, rijbewijs, BSN)?
  - Wat zijn de eisen voor een organisatie? 
- Sensor eigenaar sign up formulier + log in functionaliteit (username+password, SSO?, Google account, Github account, Azure account, Facebook account, moeten we dit soort dingen ondersteunen???)
- Sensor eigenaar portal voor het beheer van contact gegevens -> wat is er publiek van mij bekend?
- Sensor eigenaar portal overzicht van 'mijn sensoren' (lijstje? filter van 'mijn sensoren' op de kaart?)

**Comment by kad-bloemy** [comment]
In hoeverre is verificatie van een eigenaar meegenomen in het MVP?
De rest is m.i. gerealiseerd.

**Comment by marcvanandel** [comment]
Zonder verificatie is dit inderdaad gerealiseerd. Laten we verificatie - voor het MVP - buiten beschouwing laten. Later issue van opvoeren als duidelijker is wat er dan precies nodig is ...
