### ISSUE TITLE
Functionele testen tbv samenwerkingspartners meenemen in de sprint

### ISSUE THREAD

**Issue by mario-schrijver** [kadaster-labs/sensrnet-home#20]
Met de samenwerkingspartners (concreet de gemeenten Eindhoven en Apeldoorn) hebben we afgesproken dat zijn een rol krijgen in het functioneel testen van de opgeleverde functionaliteit. Het lijkt me daarom des Agiles om deze mee te ontwikkelen in de sprint en die ook in de sprint te laten uitvoeren. 

Ik denk dat we kunnen volstaan met het doen van happy flow testing als het gaat om functionaliteit.
Dat zou inhouden dat we unskilled testers hierop los kunnen laten. 

Ter discussie dus.

**Comment by marcvanandel** [comment]
Welke scenario's gaan we aan bouwen en willen we kunnen laten testen?
- #2 eigenaar kan zichzelf registreren
- #3 eigenaar kan een sensor registreren

**Comment by grusma** [comment]
> Met de samenwerkingspartners (concreet de gemeenten Eindhoven en Apeldoorn) hebben we afgesproken dat zijn een rol krijgen in het functioneel testen van de opgeleverde functionaliteit. Het lijkt me daarom des Agiles om deze mee te ontwikkelen in de sprint en die ook in de sprint te laten uitvoeren.
> 
> Ik denk dat we kunnen volstaan met het doen van happy flow testing als het gaat om functionaliteit.
> Dat zou inhouden dat we unskilled testers hierop los kunnen laten.
> 
> Ter discussie dus.

Gemeente Helmond wilt graag het testen. Tijdens bijeenkomst op 21 januari hebben dat aangegeven. "We willen dit parallel laten lopen met het project Warande Digitaal waar we mbv sensoren in de OR verschillende toepassingen zullen uitrollen".

**Comment by grusma** [comment]
> Welke scenario's gaan we aan bouwen en willen we kunnen laten testen?
> 
> * #2 eigenaar kan zichzelf registreren
> * #3 eigenaar kan een sensor registreren

Het liefst:
> * #2 eigenaar kan zichzelf registreren
> * #3 eigenaar kan een sensor registreren
en op de viewer geregisterde sensor laten zien.

Als alle 3 componenten niet mogelijk zijn zou ik focussen aan:
- sensor registreren
- op de viewer presenteren
Ik weet dat de synchronisatie tussen sensor registreren en verschijnen op de viewer kan ingewikkeld zijn. Tijdens pilot met Eindhoven was dat niet goed geregeld.

**Comment by marcvanandel** [comment]
Nou, dat moeten we toch kunnen fixen binnenkort, niet @kad-floriw en @kad-griftj ? 😃

**Comment by kad-floriw** [comment]
Lijkt mij wel ;)

**Comment by RickSchager** [comment]
@grusma: Wie vanuit Helmond coordineert de functionele testen?
@marcvanandel: Begreep dat je voor/met Ralf Tjemmes uit Apeldoorn testscripts en aanpak (of zo??) zo doornemen. Als dit is gebeurt, kan je info delen?
@marcvanandel + @mario-schrijver : Vanuit Cathy (prov Brabant) begrijp ik dat er ook een keuze is voor "testen binnen de eigen omgeving (is wat meer werk)". Is het klonen/configureren/... nu in scope? Zo ja, wat voor sandbox specs (uit MS Azure cloud?) adviseren jullie?

**Comment by grusma** [comment]
> @grusma: Wie vanuit Helmond coordineert de functionele testen?

Hoi Rick. Ik heb jouw vraag net naar Velzen, Sophie van <S.van.Velzen@helmond.nl>gestuurd.
Ik kom op jouw vraag terug.

**Comment by RickSchager** [comment]
@marcvanandel  + @mario-schrijver : hoe/wanneer realiseren  en testen we op slide 10 van 20200429 SensorRegister-SA-Roadmap-v06 (terecht) genoemde requirement: "Minimale technische features vooral gericht op het aantonen van het synchroniseren van data en aantonen dat juiste balans in decentraal en gedistribueerd en centraal werkt en flexibel is voor de toekomst".
![image](https://user-images.githubusercontent.com/28686607/83618584-f011f500-a58a-11ea-9676-de2db6edb263.png)

**Comment by grusma** [comment]
@RickSchager 
Dag Magdalena,
Voor wat betreft de coördinatie van de functionele testen van het sensorenregister, zal ikzelf het eerste aanspreekpunt zijn. Neem Henri de Bekker gerust mee in cc.

Met vriendelijke groet,
Sophie van Velzen

**Comment by marcvanandel** [comment]
@RickSchager , ik heb [hier](https://github.com/kadaster-labs/sensrnet-home/blob/master/docs/Architecture.md#test-environments) een (erg schematisch) plaatje toegevoegd die de test omgeving(en) weergeeft. Hopelijk geeft dat enige verduidelijking?

Daarnaast heb ik nog een issue open staan om te beschrijven hoe de runtime env er dan (ongeveer/precies) uit moet zien: #27

**Comment by grusma** [comment]
@marcvanandel een voorstel ter bespreking met de stakeholders
SensRNet functioneel ontwerp, use-cases (lang versie)
Doelgroepen:
Het is belangrijk om helder te maken welke behoeftes en verwachtingen van verschillende doelgroepen bij te horen.
Inwoners 
Inwoners graag willen weten waar gesensed wordt, door wie en waarom. Hoe bijv. de luchtkwaliteit / het geluidsniveau / de drukte op de weg zich ontwikkelt in zijn omgeving, informatie krijgen hoe erg/goed dat is. Ze hebben behoefte aan een goede visualisatie en informatie uit de data. De ruwe data zijn niet interessant voor de meerderheid van de inwoners. Inwoner wil ik graag weten dat hij/zij veilig op de straat kan lopen, dat er gemonitord is. Tegelijkertijd wilt hij graag geen zorgen hoeven te maken dat de data van zijn mobiel overgenomen door deren is of iemand data over hem zonder toestemming verzameld.

Als inwoner wil ik graag:
•	weten waar de sensoren zijn en wat ze doen/meten 
o	toegang tot gebruiksvriendelijk* viewer krijgen waar de sensoren op de kaart te zien zijn met pop-up met meer informatie
o	Ik kan de viewer ook op mijn mobiel raadplegen; GPS (ik sta hier) knop hebben
o	graag per thema selectie de juiste groep van de sensoren zien. 
•	weten de reden waarom sensoren/meetapparaten hier zijn en metingen doen
•	weten wie de eigenaar van de sensoren en data is
•	een vraag aan de sensor/data eigenaar kunnen stellen, contact opnemen
•	terugmelden wanneer een sensor op de kaart niet zien is; informatie ontbreekt
•	mijn eigen sensoren toevoegen/registreren

*met zoek functie, legenda, niet te drukke kaart, door in en uit te zoemen een aantal sensoren kunnen zien, luchtfoto als een optionele achtergrond,

Bedrijven, sensoreigenaren
Bedrijven (eigenaren van de sensoren) willen graag een tool, omgeving krijgen om zijn sensoren eenvoudig en snel kunnen registreren. Sommige bedrijven willen graag een makkelijk toegang tot de informatie en data van de sensoren krijgen om deze verder in zijn processen bewerken en als nieuwe produceren/diensten etc. op de markt te zetten. Informatie en toegankelijkheid tot data voor bedrijven is dus zeer belangrijk.

Als sensoreigenaar:

•	kan ik mijzelf registreren, inloggen in mijn 'Registry Node App'
o	dat doe ik alleen een keer; data over mij zijn veilig (AVG proef).
•	kan ik mijn sensoren registreren
o	ook verwijderen en updaten wanneer nodig
o	Bulk import/export
o	Afschermen open vs. vertrouwelijke sensoren
•	mijn sensoren op de kaart zien (viewer)
•	sensoren van de anderen op de kaart zien (viewer)
•	toegang tot data van de andere sensoren te krijgen wanneer mogelijk
o	Link voor (data) downloaden of API
•	terugmelden over geconstateerde onjuistheden 
•	ondersteuning krijgen wanneer ik vragen heb

Overheid, gemeentes
Voelt verantwoordelijk voor informatie over en van de sensoren en het plaatsen in openbare ruimte. Dat is niet de bedoeling dat iedereen gaat zijn eigen sensoren (kasjes) in de openbare ruimte ophangen zonder bijv. verhuring aanvraag.  Overheid wilt transparantie, betrouwbaarheid, uniformiteit garanderen. Overheid promoot een open data en zorgt voor een eenvoudig toegang tot een goede kwaliteit data.
Betrouwbaar sensor data ’s gaan overheid instanties en particulieren ondersteunen in beslissingen te maken traject(en). Overheid wil graag een sensor data vindbaar en open maken om verschillende programmas zoals Smart en Sustainable Cities ondersteunen.
*Kadaster wil graag in de versterking van de hoge data kwaliteit actief participeren (maatschappelijk verantwoord..) Actief rol nemen aan SensRNet consortium.
Testplan funcionaliteiten:
Als medewerker van een gemeente kan ik:
•	inloggen in mijn 'Registry Node App'
•	door te klikken op de kaart een locatie aangeven waar ik een sensor wil registreren
•	vervolgens kan ik alle details invullen om de sensor te registreren
•	Koppelvlak met eigen system (BOR, CMDB)

Onderwijs
Onderwijs wereld wilt graag data van de sensoren voor zijn eigen onderzoeken en analyses kunnen gebruiken. De data en metadata van de sensoren moeten dus beschikbaar en makkelijk vindbaar zijn.
Als onderzoeker wil ik graag:
•	overzicht krijgen waar de sensoren zijn en wat ze meten
•	een toegang tot data van de sensoren krijgen
•	een contact met de sensor eigenaar opnemen als ik meer vragen over data heb
•	vertrouwen aan de kwaliteit van de data/informatie
•	informatie over actualiteit ontvangen
•	terugmelden wanneer ik een onjuistheden constateert

**Comment by grusma** [comment]
@marcvanandel een voorstel ter bespreking met de stakeholders
SensRNet functioneel ontwerp, use-cases (korte versie)

**Als inwoner wil ik graag:**
• weten waar de sensoren zijn en wat ze doen/meten
o toegang tot gebruiksvriendelijk* viewer krijgen waar de sensoren op de kaart te zien zijn met pop-up met meer informatie
o Ik kan de viewer ook op mijn mobiel raadplegen; GPS (ik sta hier) knop hebben
o graag per thema selectie de juiste groep van de sensoren zien.
• weten de reden waarom sensoren/meetapparaten hier zijn en metingen doen
• weten wie de eigenaar van de sensoren en data is
• een vraag aan de sensor/data eigenaar kunnen stellen, contact opnemen
• terugmelden wanneer een sensor op de kaart niet zien is; informatie ontbreekt
• mijn eigen sensoren toevoegen/registreren

*met zoek functie, legenda, niet te drukke kaart, door in en uit te zoemen een aantal sensoren kunnen zien, luchtfoto als een optionele achtergrond,

**Als sensoreigenaar:**
• kan ik mijzelf registreren, inloggen in mijn 'Registry Node App'
o dat doe ik alleen een keer; data over mij zijn veilig (AVG proef).
• kan ik mijn sensoren registreren
o ook verwijderen en updaten wanneer nodig
o Bulk import/export
o Afschermen open vs. vertrouwelijke sensoren
• mijn sensoren op de kaart zien (viewer)
• sensoren van de anderen op de kaart zien (viewer)
• toegang tot data van de andere sensoren te krijgen wanneer mogelijk
o Link voor (data) downloaden of API
• terugmelden over geconstateerde onjuistheden
• ondersteuning krijgen wanneer ik vragen heb

**Testplan funcionaliteiten:
Als medewerker van een gemeente kan ik:**
• inloggen in mijn 'Registry Node App'
• door te klikken op de kaart een locatie aangeven waar ik een sensor wil registreren
• vervolgens kan ik alle details invullen om de sensor te registreren
• Koppelvlak met eigen system (BOR, CMDB)

**Als onderzoeker wil ik graag:**
• overzicht krijgen waar de sensoren zijn en wat ze meten
• een toegang tot data van de sensoren krijgen
• een contact met de sensor eigenaar opnemen als ik meer vragen over data heb
• vertrouwen aan de kwaliteit van de data/informatie
• informatie over actualiteit ontvangen
• terugmelden wanneer ik een onjuistheden constateert
