### ISSUE TITLE
Ondersteuning Meldplicht Gemeente Amsterdam

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#210]
Ondersteuning, hulp, vragen beantwoorden van Gemeente Amsterdam:

- [ ] #195 
- [ ] #194 ?

**Comment by kad-bloemy** [comment]
Zie [https://github.com/kadaster-labs/sensrnet-home/issues/186](url)

**Comment by marcvanandel** [comment]
De deadline voor het bieden van een formulier aan bedrijven tbv de meldplicht staat nu op 1 december 2021. Dat is te kort dag om alle uitdagingen te overkomen van ontwikkeling en deployment binnen de gemeente A'dam, laat staan om een koppeling te maken met een nog te installeren SensRNet node. Daarom gaat A'dam eerst een minimale oplossing realiseren tbv de meldplicht om deze later door te ontwikkelen cq aan te passen naar (een koppeling naar) SensRNet.

**Comment by marcvanandel** [comment]
Gemeente Amsterdam gaat eerst zonder SensRNet aan de slag om te kunnen voldoen aan de deadline tbv de invoering van de Meldplicht. Daarmee is ondersteuning vanuit SensRNet teruggebracht naar ondersteuning in (voornamelijk) datamodel.
