### ISSUE TITLE
Improving Admin in Organization existance

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#216]
When a new Organization is created the current User will be added to it and become the Admin of this Organization straight away.

What needs to happen when the one (or last) Admin tries to leave an Organization? 

- [x] the last / only Admin is not allowed to leave the Organization?
- [x] the last / only Admin should get an extra warning about an 'orphaned' Organization?

**Comment by marcvanandel** [comment]
Discussing this internally we come to the point that:

- there must always be at least ONE admin,
- so you can leave an Organization as long as you assigned the Admin role to another User
- as last User and Admin of an Organization you first need to remove all Devices before you can remove the Organization
- when all Devices are removed for the current Organization and you are the last User and Admin you'll be able to leave this Organization by removing the Organization

**Comment by marcvanandel** [comment]
Well, first steps are looking good: 
![image](https://user-images.githubusercontent.com/2315396/127618311-fd7fbdcf-b78a-49d6-8422-e61bb5893696.png)

**Comment by banaan666** [comment]
Looking good already!

**Comment by marcvanandel** [comment]
Created an 'Danger zone' dropdown and these actions first serve a popup with an 'Are you sure?' message:

![image](https://user-images.githubusercontent.com/2315396/127643962-cae2202a-7906-460e-8fb5-78ab20e007a5.png)

**Comment by marcvanandel** [comment]
Before removing an Organization all devices need to be removed. There are a few options to check whether an Organization doesn't have existing devices (anymore):

1. Persist a new view with number of (or IDs of) devices registered for this Organization; this has to be `0` (of course)
2. Produce events on the `LegalEntity` for each device registered. By doing so the relation between Legal Entity and Device is explicit and can be loaded from the events. In the state of the Legal Entity the number of existing devices can be checked before removal
