### ISSUE TITLE
Product Vision NL toevoegen

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#26]
NL versie van [ProductVision.md](https://github.com/kadaster-labs/sensrnet-home/blob/master/docs/ProductVision.md)

**Comment by kad-bloemy** [comment]
Milestone MVP: wat is de status hiervan? Kan ik hierin iets doen?

**Comment by marcvanandel** [comment]
Ja, de Engelse versie kan wel een review gebruiken, denk ik, en een Nederlandse versie bestaat nog helemaal niet. Dit kan gewoon opgepakt worden 😉

**Comment by kad-bloemy** [comment]
Zie [https://github.com/kadaster-labs/sensrnet-home/blob/main/docs/Productvisie%20-%20NL.md](url)

**Comment by kad-bloemy** [comment]
Verbeterde naamgeving: [https://github.com/kadaster-labs/sensrnet-home/blob/main/docs/ProductVisionNL.md](url)
