### ISSUE TITLE
Schrijven beheerdershandleiding

### ISSUE THREAD

**Issue by CelineJansen** [kadaster-labs/sensrnet-home#263]
Hoe beheer je apparaten, sensoren, en datastromen in het sensorenregister 
(SensRNet)? Gemeente Eindhoven wil een handleiding opleveren om beheerders van sensoren te 
ondersteunen bij het opvoeren, updaten en verwijderen van gegevens in SensRNet.
Let op, dit betreft dus niet per definitie alle functionaliteiten van de tool en de API, puur 
degene relevant voor het beheer van de vakinhoudelijke gegevens. 

Voorzetje (let op: nog niet af, zwaar conceptueel en puur voor het idee):
[HandleidingSensRNet_NIETAF.pdf](https://github.com/kadaster-labs/sensrnet-home/files/7539449/HandleidingSensRNet_NIETAF.pdf)

**Comment by marcvanandel** [comment]
Super input, @CelineJansen !!! @kad-bloemy is hier ook al mee bezig in #250.

@kad-bloemy , neem je de input van Celine mee in jouw PR?

**Comment by kad-bloemy** [comment]
Goede aanzet! Zie ook [Gebruikerdoc](https://github.com/kadaster-labs/sensrnet-home/tree/gebruikerdoc/docs) Ik hoop dat je erbij kunt. Open de file DocumentationNL

**Comment by marcvanandel** [comment]
Wat is de beheerdershandleiding anders dan #160 (gebruikershandleiding)?

**Comment by CelineJansen** [comment]
De beheerdershandleiding heeft als scope te ondersteunen bij wat de beheerders nodig hebben om hun sensoren actueel te houden in SensRNet. Er zal behoorlijk wat overlap zijn met andersoortig gebruik, maar de focus kan anders zijn. Een gebruiker die puur wil weten waar allerlei sensoren zich op dit moment bevinden heeft andere dingen nodig dan een beheerder die de velden daadwerkelijk bij wil werken. De beheerdershandleiding is dus eigenlijk een gebruikershandleiding met als scope het specifieke type gebruik "beheren van sensoren".

**Comment by marcvanandel** [comment]
Aha. Beheerdershandleiding is de Registry Node gebruikershandleiding, right? Ik denk dat wij met #160 hetzelfde bedoelden ... 😄 Dat maakt niet uit, maar dan weten we dat we aan hetzelfde werken ... en wellicht goed om dat dus duidelijker te maken! 👍

**Comment by CelineJansen** [comment]
Nieuwe versie van de beheerdershandleiding, nog steeds niet volledig (ik wil nog een stuk toevoegen over het wijzigen van gegevens met de API). Methodiek en scripts voor bulk opvoer en bulk verwijderingen wordt nu wel beschreven (vanaf pagina 14). Scripts + templates staan in https://github.com/kadaster-labs/sensrnet-home/issues/176.

Feedback is welkom.

[HandleidingSensRNet_NIETAFv2.pdf](https://github.com/kadaster-labs/sensrnet-home/files/7635454/HandleidingSensRNet_NIETAFv2.pdf)

**Comment by marcvanandel** [comment]
Eerste versie is 'merged' in de documentatie ... maar er komen nog updates 😉

**Comment by CelineJansen** [comment]
Zie ook https://kadaster-labs.github.io/sensrnet-home/UserManualNL/ voor de documentatie.

**Comment by marcvanandel** [comment]
De handleiding is opgeleverd (en van hoge kwaliteit !!) Het laatste stukje dat nog moet gebeuren is de handleiding die @kad-bloemy aan het maken was _ín_ deze handleiding toe te voegen. Met name de waardelijsten zijn van toegevoegde waarde

**Comment by CelineJansen** [comment]
De eerste complete versie van de beheerdershandleiding inclusief scripts en waardelijsten is terug te vinden onder: https://kadaster-labs.github.io/sensrnet-home/UserManualNL/.
