### ISSUE TITLE
Community pagina toevoegen aan documentatie site

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#272]
Gemeente Nijmegen heeft actief bijgedragen aan het datamodel, net zoals Gemeente Eindhoven in een eerder traject al en in details én actief in de gebruikers-/beheerdersdocumentatie. Natuurlijk zijn BrabantStad en individuele gemeenten daarin, de provincie ook actief betrokken. En alle andere gemeenten die op enige manier bijdragen, betrokken zijn, deelnemen aan de community. En overige partijen ...

Dit wordt snel een lange lijst waarin het moeilijk is duidelijk te maken wie hoeveel participeert en bijdraagt, zowel in tijd als in geld als in kennis als in ... 

Hoe kunnen we het beste laten zien dat SensRNet een groeiende community is van verscheidene overheidspartijen op meerdere niveaus en gezamenlijk het doel hebben om verrommeling van de openbare ruimte te voorkomen en transparantie naar de burgers in Nederland te voorzien van informatie?

**Comment by CelineJansen** [comment]
Misschien een pagina met betrokken partijen binnen https://kadaster-labs.github.io/sensrnet-home/? Eventueel incl. een gallery / gastenboek waar men zelf usecases of aanvullingen kan posten (al is daarbij een risico dat men dit slecht weet te vinden en het leeg blijft, wat dan weer jammer is)?

**Comment by marcvanandel** [comment]
Toevoegen onder kopje 'Contributing'? (een goed idee van @CelineJansen !!)

**Comment by marcvanandel** [comment]
Zou dit zo wat zijn? Hoe kunnen we voorkomen dat er met scheve ogen gekeken gaat worden? 🤔 

![image](https://user-images.githubusercontent.com/2315396/160273136-f5a0db64-7941-4761-9b63-ff5b9a2c98ce.png)

**Comment by CelineJansen** [comment]
Bovenstaande is wat mij betreft super (ik ben natuurlijk niet echt objectief maar toch ;)). Om aan te geven dat iedereen die wil ook daadwerkelijk betrokken kán zijn (en dus op deze pagina kan komen/scheve ogen voorkomen) kunnen jullie er misschien boven zetten dat als je wil contributen je op github mee kan denken + eventueel het sensornet email adres vermelden tbv aanmelding oid?

**Comment by marcvanandel** [comment]
Zijn de titels 'Committers' (met typo zie ik net 😆 ) en 'Contributors' duidelijk? Of zou het beter 'Initiatiefnemers' en 'Community' kunnen zijn? Wat denk jij @CelineJansen ?

**Comment by CelineJansen** [comment]
Persoonlijk vind ik beide prima. Maar in het Nederlands lijkt het me wel het mooiste om er "Initiatiefnemers" van te maken met daaronder Brabantstad, Kadaster, en BZK. En dan kan het onderscheid tussen contributors en community dat nu gemaakt wordt inderdaad ook wel komen te vervallen. Wat mij betreft past dat ook allemaal wel onder een kopje "community", maakt het minder gedetailleerd maar wel simpeler.
