### ISSUE TITLE
Device locatie naam / omschrijving komen niet beide voor in de API?

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#280]
### Discussed in https://github.com/kadaster-labs/sensrnet-home/discussions/278

<div type='discussions-op-text'>

<sup>Originally posted by **CelineJansen** December 16, 2021</sup>
Wanneer ik via https://demo.sensorenregister.nl/api/device?legalEntityId=61267b03-9024-4e90-9366-c0eebaed1123 de actuele stand van mijn organisatie uit het register op wil halen,  lijkt het alsof de naam + beschrijving van een locatie nooit beide gevuld zijn. Ook niet als dat in de UI wel zo is. 

Description lijkt alleen aanwezig als er geen naam gevuld is. Is er wel een naam gevuld, dan is description niet aanwezig in de response. Weten jullie misschien waar dit aan ligt?

Voorbeeld stukje uit de response:

   "locationDetails":{
      "name":"OudeStadsgracht-designhuis"
   }

(ID device: 25a23d9f-1f67-49e4-92bf-619b9c8d24d8)
</div>

**Comment by CelineJansen** [comment]
Uiteindelijke probleem:
Wanneer ik het probeer te reproduceren door ergens zowel naam als beschrijving te vullen in de tool doet hij het volgende:
[15:57 - er staat alleen een beschrijving]
image

[15:58 - naam toegevoegd en opgeslagen]
image

Als ik dan terug ga door op "apparaten" te klikken, en dezelfde device weer zoek. Staat er alleen nog maar een naam. De beschrijving is dan verdwenen.
image

als de velden al eens ingevuld zijn lijkt er nu 1 van de 2 te verdwijnen bij het opslaan (maar niet als de velden nog niet zijn ingevuld).

**Comment by kad-busses** [comment]
Er stond al een PR klaar (https://github.com/kadaster-labs/sensrnet-registry-backend/pull/144), ik neem aan dat die hier voor is
