### ISSUE TITLE
Registry: Onderscheid tussen users en organizations

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#46]
Owner is een 'oude' entiteit(naam). Het model gewijzigd naar 'Organization' (zie [views](https://github.com/kadaster-labs/sensrnet-home/blob/master/docs/Model.md#views)) met als 'role' die van (bijv.) 'sensor-owner'.

Met dit issue gaan we:
- [x]  Hernoemen 'Owner' naar 'Organization' ([UK vs US](https://www.quora.com/Whats-the-difference-between-organization-and-organisation#:~:text=Organization%20and%20organisation%20both%20are,is%20used%20in%20British%20english.&text=In%20America%20English%2C%20it%20is,English%20it%20is%20spelled%20Organisation.))
- [x] Toevoegen 'role' aan `Sensor` á la latest [Event Modeling](https://raw.githubusercontent.com/kadaster-labs/sensrnet-home/master/images/SensRNet-Event-Modeling-v20201102.jpg)
- [x]  Frontend aanpassen 'Owner' naar 'Organization' incl. claimen van 'ownership' van sensoren?

Oorspronkelijk uit testdag#1.

Op dit moment is een login gelijk aan een owner. In het model is er onderscheid tussen users (gebruikers) en de organisatie die eigenaar is. Hiervoor komt nog functionaliteit incl. beheer van gebruikers onder een eigenaar (owner).

**Comment by kad-vossef** [comment]
Verder specificeren door ARCH en FAB
