### ISSUE TITLE
Registry Node on AKS deployment cookbook opstellen tbv pilotgroep

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#66]
Als deelnemer / bronhouder (bijv. gemeente) wil ik graag een node gaan draaien. Daarvoor heb ik documentatie nodig en wil ik graag gebruik maken van de scripts en tools die het Product Development Team zelf gebruikt.

De behoefte is - voor MVP - beperkt tot Azure / AKS

**Comment by marcvanandel** [comment]
@kad-busses, zouden we een `sensrnet-secrets` repo kunnen aanmaken en de `sensrnet-ops` repo (met 'flushed history') public kunnen maken? Is dat een goed idee?

**Comment by marcvanandel** [comment]
Eerste oplevering (samenvatting uit `sensrnet-ops`) in home repo: [Deployment.md](https://github.com/kadaster-labs/sensrnet-home/blob/master/docs/Deployment.md#deployment-steps)

**Comment by kad-busses** [comment]
Nieuwe interne repo aangemaakt voor secret beheer 👍

**Comment by marcvanandel** [comment]
Eerste versie gepubliceerd ...

**Comment by kad-busses** [comment]
https://github.com/kadaster-labs/sensrnet-ops is nu public
