### ISSUE TITLE
AzureAD integratie voor Registry Node (voor gebruikers incl. mapping naar organization per domeinnaam van accounts)

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#70]

**Comment by kad-busses** [comment]
Voor toevoeging van AzureAD in de registry node zijn 3 acties nodig (volgend uit vooronderzoek in https://github.com/kadaster-labs/sensrnet-home/issues/105):

- [ ] Toevoegen van een App Registratie in de juiste AzureAD tenant. Dat zijn de groep gebruikers die toegang krijgen tot de afgeschermde endpoints
- [ ] Authenticatie in de NestJS back-end. Hier dient gebruik gemaakt te worden van https://www.npmjs.com/package/passport-azure-ad om de token te kunnen verifiëren bij Microsoft. Er zijn hier twee scenarios in: 
  - [ ] Gebruik van front-end. Hier is dan de BearerStrategy voor nodig, die de opgestuurde token verifieert bij Azure.
  - [ ] Gebruik van de Swagger interface in de back-end. Het is nog niet helemaal helder of dit op dezelfde manier gaat als bij de eigen front-end, of dat hier gebruik moet worden gemaakt van de OIDCStrategy. Dit scenario heeft verdere uitwerking nodig, al is het aannemelijk dat de vereiste kennis bij het uitwerken van het vorige punt wordt opgedaan. In dat geval wordt dit lijstje aangepast aan de hand van de verkregen inzichten.
- [ ] Authenticatie in de front-end. Dit gebeurt met [MSAL.js](https://github.com/AzureAD/microsoft-authentication-library-for-js). De verkregen token wordt naar de back-end verstuurd.

Note: Meerdere authenticatie strategieën zijn mogelijk. Voor het testen kan het bijvoorbeeld wenselijk zijn om zowel AzureAD als losse username/password toe te staan, maar in productie enkel AzureAD

**Comment by kad-busses** [comment]
Implementatie opgeleverd voor het generieke geval van integratie met OpenId Connect providers (waarbij AzureAD een optie is). De token wordt verkregen in de frontend, de backend verifieerd die. Documentatie en instructies voor deployment zijn aangepast.
