### ISSUE TITLE
Lijst van type ObservedProperties verzamelen

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#74]
Bijvoorbeeld op basis van CBS info van verschillende contexten waarin / doelen waarvoor sensoren worden ingezet.

ObservedProperties gebruiken we als 'het abstracte niveau van feature of interest'; waar zijn we in geïnteresseerd en waarom?

Bij voorkeur is dit redelijk beperkt tot ca. 20 items.

**Comment by marcvanandel** [comment]
Thema's van [data.overheid.nl](https://data.overheid.nl/)?

**Comment by RickSchager** [comment]
Of bij https://gitlab.com/synchronicity-iot/synchronicity-data-models kijken.
Met onder tabelleke met links naar FIWARE (meta) data modellen.
Voor luchtkwaliteit = https://github.com/FIWARE/data-models/blob/master/specs/Environment/AirQualityObserved/doc/spec.md

**Comment by marcvanandel** [comment]
Input van Rob:

Opendata blijkt overigens wel iets meer thema’s te beschrijven. Ik ben wat dieper aan het zoeken en zie dat ze heel info geven over andere entiteiten, zoals organisaties, openbaarheidsniveau, etc. : DCAT-AP-DONL — Waardelijsten (dcat-ap-donl.nl)
 
Voor ons doel is nu de taxonomieBeleidsagenda interessant: overheid:TaxonomieBeleidsagenda | StandaardenOverheid.nl en specifieker: Thema-indeling voor Officiële Publicaties (TOP-lijst) | StandaardenOverheid.nl
 
Deze zijn dus ook als dataset beschikbaar (XML, RDF, JSON en TTL) én worden door KOOP (BZK-beheerclub) beheerd en bijgehouden. Ik weet niet wat makkelijker is voor de MVP; deze inbouwen/koppelen of zelf een subset bouwen. Mijn gevoel zegt dat het eerste wenselijk is, maar ik kan technisch niet beoordelen of dat haalbaar is voor de MVP.

**Comment by kad-bloemy** [comment]
Volgens SensorThingsAPI is ObservedProperty het gemeten phenomeen van de Datastream, met als voorbeeld "dewpoint temperature", die gemeten wordt met een thermometer (=sensor). Het lijkt dus het doel van de meting. In ons huidige model hebben we geen mogelijkheid om dit aan te geven. Wat hierboven beschreven staat heeft eerder betrekking op Theme (in Datastream), of zelfs Description (lijst in Sensor). Voorstel om ObservedProperty op te nemen als eigenschap van Datastream.

**Comment by kad-bloemy** [comment]
Zie ook https://github.com/kadaster-labs/sensrnet-home/issues/75

**Comment by kad-bloemy** [comment]
Voorstel dit issue te sluiten
