### ISSUE TITLE
Lijstje van ObservedProperties filteren voor MVP op basis bestaande metadata van sensoren

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#75]
In #74 verzamelen we een lijstje van ObservedProperties. Om focus te krijgen voor eerst realisatie (MVP) gaan we de huidige registratie van sensoren tegen dit lijstje houden om te zien welke we als eerste moeten realiseren. Dat is met de nu betrokken bronhouders.

**Comment by kad-bloemy** [comment]
Volgens SensorThingsAPI is ObservedProperty het gemeten phenomeen van de Datastream, met als voorbeeld "dewpoint temperature", die gemeten wordt met een thermometer (=sensor). Het lijkt dus het doel van de meting. In ons huidige model hebben we geen mogelijkheid om dit aan te geven. Wat hierboven beschreven staat heeft eerder betrekking op Theme (in Datastream), of zelfs Description (lijst in Sensor). Voorstel om ObservedProperty op te nemen als eigenschap van Datastream.

**Comment by kad-bloemy** [comment]
ObservedProperty is nu ObservationGoal met vrij invoerveld. Zie [https://github.com/kadaster-labs/sensrnet-home/issues/77](url)

**Comment by marcvanandel** [comment]
(en daarmee opgelost, toch?)
