### ISSUE TITLE
Datamodel: ObservedProperty vs FeatureOfInterest

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#77]
In de [SensorThingsAPI](https://en.wikipedia.org/wiki/SensorThings_API) ([OGC Documentation](http://developers.sensorup.com/docs/#introduction)) zijn twee entiteiten die relevant lijken voor SensRNet, het nationale sensorenregister: [ObservedProperty](http://developers.sensorup.com/docs/#observedProperties_post) en [FeatureOfInterest](http://developers.sensorup.com/docs/#featureOfInterest). Voor SensRNet is het van belang om doel / context van 'sensing' te kunnen duiden, koppelen en daarvoor is 'het gebied van interesse' van een sensor of meer nog, de datastromen uit een sensor(kastje) van toepassing. In ons begrip van FeatureOfInterest lijkt deze van toepassing ... hoewel deze gekoppeld is aan Observation, wat - volgens ons begrip - de meting is. Aangezien in SensRNet geen sensordata wordt vastgelegd, is dit een 'zwevende' entiteit in dit model. ObservedProperty past dan beter.

In de [FAB](https://github.com/kadaster-labs/sensrnet-home/blob/master/docs/FAB.md) sessie van 18 nov 2020 hebben we gekozen om *ObservedProperty* te nemen als 'koppel entiteit' voor sensorenregister doelen en daarin een soort samenvoeging te doen met FeatureOfInterest (maar deze verder niet mee te nemen in het model).

**Comment by kad-bloemy** [comment]
Volgens SensorThingsAPI is ObservedProperty het gemeten phenomeen van de Datastream, met als voorbeeld "dewpoint temperature", die gemeten wordt met een thermometer (=sensor). FeatureOfInterest is de verbijzondering van de plek waar je dat meet, met als voorbeeld omschrijving "This is CCIT #361, Noah’s dad’s office", met polygoon. ObservedArea is (de bounding box van) het totaal aan FeaturesOfInterest van alle Observations. Location is de plek waar het Device staat en kan gelijk zijn aan FeatureOfInterest. Bijvoorbeeld bij een kamerthermostaat zijn beide gelijk.

**Comment by kad-bloemy** [comment]
Voorstel om FeatureOfInterest te laten vervallen.

**Comment by kad-bloemy** [comment]
In SensorThingsAPI is ObservedProperty een entiteit met een relatie naar Datastream: een Datastream kan altijd maar één ObservedProperty betreffen. Een ObservedProperty kan bij meerdere Datastreams horen. Wij hebben ObservedProperty gemodelleerd als eigenschap van Observation. Dit suggereert dat bij één Datastream meerdere Observations horen, die allemaal een andere ObservedProperty hebben. Dit kan niet de bedoeling zijn. Voorstel om ObservedProperty als eigenschap van Datastream op te nemen.

**Comment by kad-bloemy** [comment]
ObservedProperty is nu als ObservationGoal opgenomen in het datamodel. Hierin kan een naam en omschrijving worden ingevuld en bovendien wordt de (wettelijke) grondslag hierin opgenomen, zoals een gemeentelijke verordening of een privacyverklaring. Naast een tekst is er ruimte voor een link naar informatie die elders staat (URL).

**Comment by marcvanandel** [comment]
(en daarmee is dit issue opgelost, toch?)
