### ISSUE TITLE
Datamodel: (File)Format definiëren voor het vastleggen en onderhouden van definities

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/sensrnet-home#79]
Op dit moment zijn we - met name Rob van Gemeente Nijmegen - bezig met het vastleggen van definities in het datamodel. De vraag daarbij is welk (file)format daarbij goed ondersteunt.

In branch [`model-definitions`](https://github.com/kadaster-labs/sensrnet-home/tree/model-definitions) heb ik vier verschillende formats gezet:

- Markdown: [Definitions.md](https://github.com/kadaster-labs/sensrnet-home/blob/model-definitions/docs/Definitions.md)
- reStructuredText: [Definitions.rst](https://github.com/kadaster-labs/sensrnet-home/blob/model-definitions/docs/Definitions.rst)
- CSV: [definitions.csv](https://github.com/kadaster-labs/sensrnet-home/blob/model-definitions/docs/definitions.csv) (te bewerken met MS Excel)
- JSON: [definitions.json](https://github.com/kadaster-labs/sensrnet-home/blob/model-definitions/docs/definitions.json)

De eerste twee formats zijn 'text based human readable' file formats, waarbij reStructuredText mogelijkheden heeft om 'multi line' cellen te gebruiken en Markdown niet (waardoor tabellen veel te groot of onoverzichtelijk worden ... maar dat is misschien - in dit geval - voor reStructuredText ook wel zo?)

De laatste twee formats zijn meer technische formaten die mbv extra tools als HTML table gepresenteerd kunnen worden ... maar wel deze extra tools nodig hebben.

Voordeel van bovenstaande formaten boven `.xslx` (MS Excel) formaat, is dat versiebeheer per regel mogelijk is in GitHub. Voor de initiële publicatie niet zo relevant, wel voor opvolging daarna. Dan is het fijn om per regel een issue te kunnen maken met afwegingen en te kunnen zien wat er nu precies verandert. Daarom is het JSON formaat misschien nog wel het meest handig? Of anders de reStructuredText formaat?

**Comment by RickSchager** [comment]
Wat mij betreft het liefst JSON. a la https://github.com/FIWARE/data-models

**Comment by robhaans** [comment]
Ik ben hiervoor niet technisch genoeg, maar ik kan json-bestanden echt niet fatsoenlijk lezen. Ik heb gewoon een tabel nodig, in wat voor tool dan ook.

**Comment by marcvanandel** [comment]
@robhaans top dat je comments toevoegt!!

Is de reStructuredText format wel een optie (dat is de `Definitions.rst` variant) ? Er is goede documentatie over te vinden online (bijv. [hier](https://docutils.sourceforge.io/docs/user/rst/quickref.html))

**Comment by robhaans** [comment]
Ja, die snap ik wel. Geeft ook in een editor nog een visueel gevoel. Werkt Trello hier ook niet mee?

**Comment by marcvanandel** [comment]
Dat weet ik niet zeker ... maar zie wel veel 'hits' als ik daar naar zoek 😉 

Ik wil `Definitions.rst`  nog wat verbeteren, want ik vind de tabel nog te breed. Ik denk dat dat een goede manier is om de definities bij te houden. In ieder geval voor nu (of wanneer we met elkaar vinden dat de Excel 'af genoeg' is)

**Comment by marcvanandel** [comment]
reStructuredText gekozen en v6 van de definitions toegevoegd. Nog steeds als basis om nog verder te verbeteren qua tekstuele layout in de file zelf. Output (in GitHub) ziet er prima uit nu ...

**Comment by robhaans** [comment]
De cursieve elementen hadden er nog niet bij gehoeven, die waren meer voor achter de hand te houden.

**Comment by robhaans** [comment]
Ik blijf ermee zitten dat ik geen idee heb hoe ik nu aanpassingen kan doen aan de definitielijst. Ik wil gewoon een editor zien waarin ik aanpassingen kan doen. Of een cursus Github/Visual studio.

**Comment by marcvanandel** [comment]
Check. Dat is wel een goed idee voor volgend jaar, denk ik. Een cursus / gezamenlijke training on the job:

- Hoe doe ik GitHub?
- Hoe doe ik VSCode?

**Comment by RickSchager** [comment]
Copy that,  I'm in!

**Comment by marcvanandel** [comment]
Issue #120 aangemaakt om een online training te gaan organiseren (in het nieuwe jaar 😉 )

Daarnaast heb ik de cursieve regels aangeduid in een nieuwe kolom: `in MVP` (zie PR)

**Comment by marcvanandel** [comment]
Wat denk je, @robhaans, zal ik deze maar mergen? 

_(daarmee bedoel ik dat we PR #72 sluiten en de bestanden opnemen in de `master` waarmee het standaard terug te vinden is. Dat is dan ook gelijk de aanzet om die definities daar bij te houden. Daar wil ik aankomende maanden nog wel extra support op leveren door die wijzigingen bij te houden in GitHub terwijl jij (en anderen) nog in de Excel werken) 😉 )_

**Comment by robhaans** [comment]
@marcvanandel Ok, prima. Ik lever gewoon wijzigingen aan in excel die jij dan verwerkt. Sluit dan maar. Wordt dan ook het stukje definities aangepast wat nu in de master staat?

**Comment by marcvanandel** [comment]
Yup!
