### ISSUE TITLE
Set up comp 4: Centrale viewer

### ISSUE THREAD

**Issue by grusma** [kadaster-labs/sensrnet-home#9]
Een omgeving waar sensoren (meetapparatuur/actuatoren/cameras/beacons etc. ) zichtbaar zijn en waar iedereen informatie kan vinden waar, wie en waarom.
viewer voorbeelden:
- pilot Kadaster/Eindhoven
-https://slimmeapparaten.amsterdam.nl/
-https://samenmeten.rivm.nl/dataportaal/

Het idee is om bestaande componenten zo veel mogelijk (re)gebruiken
- Op de viewer kan een selectie gemaakt worden wat man op de kaart wilt zien (legenda met apparaten - voorbeeld Amsterdam)
- zoek balk, in/uit scrollen (met muis)
- "groeperen functie": van de afstand een punt met een cijfer zien, met inzoomen helderheid welke apparaten waar zich bevinden (voorbeeld Amsterdam)
- op sensoren te kunnen klikken om meer informatie over sensor/apparaten te krijgen
welke informatie op de balkje/wolkje?/pop-up icoontje
Wat is dat? (Amsterdam voorbeeld)
camera
sensor
beacon
actuator
slimme verkeersinformatie (?)
...
Categorie eigenaar (4 mogelijkheden): 
1. publiek - naam organisatie (mogelijkheid om contact te nemen, zie voorbeeld Amsterdam)
2. private - naam bedrijf (mogelijkheid om contact te nemen, zie voorbeeld Amsterdam)
3. publiek&private - namen (mogelijkheid om contact te nemen, zie voorbeeld Amsterdam)
4. particulier
Wat doet de sensor/apparaat?
Omschrijving: 
Voor welk doel?
Omschrijving:
"Meer informatie link" - zoals in de viewer van de pilot Eindhoven-Kadaster
Onder meer informatie:
-...

**Comment by marcvanandel** [comment]
Info van Johan:

De BGT data wordt gepubliceerd via PDOK en nergens anders. Er is geen viewer oid. Dat betekent dat 'onze component 4' zelf nog een viewer moet worden. Wel zouden we gebruik kunnen maken van de generiek geo-componenten, zeker als deze echt open source worden (zijn nu alleen _als_ open source intern bij Kadaster gepubliceerd 😏 )
