### ISSUE TITLE
Datamodel - Coördinaten sensorlocatie

### ISSUE THREAD

**Issue by kad-bloemy** [kadaster-labs/sensrnet-home#93]
Oorspronkelijke vraag:

Hoe moeten coördinaten van de sensorlocatie worden opgenomen? Nu is voorzien in afzonderlijke x-, y- en z-coördinaat. In SensorThings API zijn deze samengevoegd tot één kenmerk, "coordinates". Bestaat hiervoor een standaard?

Besluit: we volgen de SensorThingsAPI, dus een array van `[x, y, z]`

- [ ] Code controleren of overal nu `[x, y, z]` wordt gebruikt.
- [ ]  Documentatie UML model bijwerken

**Comment by marcvanandel** [comment]
Hier zijn zeker standaarden voor ... maar ik weet niet welke voor ons allemaal relevant zijn. Het heeft in ieder geval te maken met de '[Map Projection](https://en.wikipedia.org/wiki/Map_projection)'. In Nederland wordt de [EPSG:28992](https://epsg.io/28992) projectie meestal gebruikt. `latitude` en `longitude` is een veelgebruikt alternatief dat op dit moment ook in onze code toegepast wordt ...

**Comment by RickSchager** [comment]
Next to these standard @ EU/International level:
Uit (https://github.com/FIWARE/data-models/blob/master/specs/Device/Device/doc/spec.md)
location : Location of this device represented by a GeoJSON geometry of type point.
•	Attribute type: GeoProperty. geo:json.
•	Normative References: https://tools.ietf.org/html/rfc7946
•	Optional.
En in deze norm ref:
GeoJSON uses a geographic coordinate reference system, World Geodetic System 1984, and units of decimal degrees.

**Comment by RickSchager** [comment]
Zie niet standaard veel de z, coördinaat

**Comment by marcvanandel** [comment]
Er is geen reden om projecties toe te passen. Daarmee kunnen we de SensorThingsAPI standaard volgen. Het is prima om daar een array van `[x, y, z]` voor te gebruiken (zoals de standaard).

-> model + code aanpassen (en documenteren) naar de standaard

**Comment by marcvanandel** [comment]
Daarnaast komt naar boven dat de locatie niet altijd gewenst is als precies gegeven. Bijvoorbeeld als het burger sensor(datastreams) betreft, is de precieze locatie wellicht minder prettig. Of beveiligingscamera's e.d. We hebben besproken dat de locatie dan afgeleid cq random gemaakt moet worden van de `ObservationArea` (is dat voldoende en mogelijk?)

Zie ook #104

**Comment by marcvanandel** [comment]
- [ ] Code controleren of overal nu `[x, y, z]` wordt gebruikt.
- [ ]  Documentatie UML model bijwerken

**Comment by kad-bloemy** [comment]
FAB 16-12-2020
-> besluit: akkoord dat we locatie als array [x, y, z] gaan gebruiken. In de code is dit (meestal?) al het geval; in de documentatie moet het nog worden aangepast.

Rondom locatie kwam ter sprake dat er ook geheime sensoren (home#8) en sensoren van burgers ooit eens in het register toegevoegd gaan worden en dan is een precieze locatie onwenselijk ... maar wel enige indicatie. Daarvoor is issue home#107 toegevoegd met daarin de suggestie om als locatie het midden van de ObservationArea (zie ook home#104) te gebruiken in de kaart viewer. Dat betekent dat het veld location optioneel moet zijn in het datamodel.

**Comment by kad-busses** [comment]
Deze issue heeft iets verdere verduidelijking nodig.

Binnen de GeoJSON spec wordt er namelijk inderdaad een array gebruikt voor coördinaten, alleen zie ik zojuist dat z optioneel is ([link](https://tools.ietf.org/html/rfc7946#section-3.1.1)). Zowel [x, y] als [x, y, z] zouden daarom acceptabel zijn volgens de standaard.

Mijn vraag is dan ook: Willen we ook [x, y] toestaan?

**Comment by kad-floriw** [comment]
Closed by #https://github.com/kadaster-labs/sensrnet-registry-backend/pull/79

**Comment by lhuisman** [comment]
Misschien goed om het besluit nog even te toetsen bij de NSGI, de autoriteit voor coordinaten(systemen) in Nederland. Zij adviseren ook de diverse basisregistraties en geo-standaarden over de juiste keuze en formulering. https://www.nsgi.nl/

**Comment by marcvanandel** [comment]
Issue #143 aangemaakt om deze verificatie te doen. Bedankt voor de comments en bijdrage! @lhuisman
