### ISSUE TITLE
Datamodel: "aim" van sensor --> "legal ground" van datastream

### ISSUE THREAD

**Issue by robhaans** [kadaster-labs/sensrnet-home#95]
In het huidige datamodel wordt "aim" gekoppeld aan een sensor, als een link naar de wettelijke grondslag van de sensor. Hoewel er besluitvorming plaats kan vinden voor het plaatsen van de sensor, is de sensor zelf nooit het onderwerp van de besluitvorming, maar hetgene de sensor meet. De grondslag moet dan ook niet gekoppeld worden aan de sensor, maar aan de datastream. Ook stellen we voor deze entiteit te hernoemen naar "legal ground".

**Comment by marcvanandel** [comment]
Akkoord als het doel wel ergens anders wordt vastgelegd, bijv. #77 `ObservedProperty` of `FeatureOfInterest`

**Comment by RickSchager** [comment]
Misschien een koppelen aan maatschappelijke opgave. zoals vastgelegd in college programma, of achter Principe 1"Van maatschappelijke waarde' uit https://vng.nl/sites/default/files/2019-11/09a-bijlage-principes-voor-de-digitale-samenleving.pdf

**Comment by marcvanandel** [comment]
Doel moeten we op een of andere manier wel vastleggen, maar daar is totaal geen eenduidig beeld over, niet rondom sensoren, maar ook niet op andere terreinen. Soms worden daar hoge maatschappelijke doelen genoemd en soms juist heel technisch of zelfs een applicatie.

Is voor het MVP `theme` (#97 ) en `legal ground` voldoende?

**Comment by RickSchager** [comment]
> Doel moeten we op een of andere manier wel vastleggen, maar daar is totaal geen eenduidig beeld over, niet rondom sensoren, maar ook niet op andere terreinen. Soms worden daar hoge maatschappelijke doelen genoemd en soms juist heel technisch of zelfs een applicatie.
> 
> Is voor het MVP `theme` (#97 ) en `legal ground` voldoende?

Voor mij wel

**Comment by marcvanandel** [comment]
@kad-bloemy , deze is toch ook al klaar?

**Comment by kad-bloemy** [comment]
Legal ground in entiteit Datastream opgenomen, waarin de wettelijke grondslag, bijvoorbeeld een vergunning kan worden vastgelegd. In de entiteit Observation is Description opgenomen, wat verwijst naar het doel van de waarneming, bijvoorbeeld camera, debietmeter, hoogtemeter, weerstation.

**Comment by kad-bloemy** [comment]
LegalGround is opgenomen in een nieuwe entiteit ObservationGoal, met een vrij invoerveld en ruimte voor verwijzingen naar verordeningen, vergunningen etc. Zie ook #77.
