### ISSUE TITLE
Datamodel: samenvoegen Type en alle Typedetails + beperken tot technische types

### ISSUE THREAD

**Issue by robhaans** [kadaster-labs/sensrnet-home#96]
Een typering van een sensor kan waarde toevoegen door iets te zeggen over de technische mogelijkheden en beperkingen van de sensor in het meten. De huidige indeling met types en Typedetails is onnodig complex: Er is maar 1 subtype Beacon en 3 subtypes camera, die allen functioneel van aard zijn.

Voorstel is om één lijst met types sensoren te maken, met IMGeo als basis:

- camera
- debietmeter
- hoogtedetectieapparaat
- detectielus
- weerstation
- flitser
- waterstandmeter
- windmeter
- lichtcel
- GMS sensor

Plus die van de huidige types:

- radar detector
- Fijnstofmeter
- UV sensor
- Lichtmeter
- Bewegingssensor
- Branddetector
- Waterniveaumeter
- Geluidsmeter
- Hoogtemeter
- Camera (vast)
- Camera (beweegbaar)
- Beacon

**Comment by marcvanandel** [comment]
Akkoord in FAB overleg van vandaag (dd 2 december 2020).

Dat moet nu wel verwerkt worden in de code en documentatie

**Comment by kad-bloemy** [comment]
Dit is als volgt gemodelleerd in het datamodel: Description in Sensor bevat de soort sensor, bijvoorbeeld Camera (vast), Camera (beweegbaar), Debietmeter, Hoogtemeter etc. Theme in Datastream bevat de functionele classificatie van de datastroom, bijvoorbeeld: Energie, Transport, Lucht, Klimaatverandering.

**Comment by kad-bloemy** [comment]
Device/Thing/Sensorinstallatie krijgt een hoofdcategorie: Sensor, Camera of Beacon. Sensor zelf  krijgt een SensorType, volgens bovenstaande opsomming. Er is verschillende malen aangegeven dat er een categorie "Overige" zou moeten komen met een vrij invoerveld, dat kan leiden tot uitbreiding van de opsomming. Dit laatste betekent dat er mogelijk wat wildgroei optreedt, maar heeft als voordeel dat de lijst kan groeien als er meerdere keren hetzelfde type wordt ingevuld. Anderzijds moet voorkómen worden dat er een eindeloze lijst doorgescrolld moet worden om het juiste type te kiezen.

**Comment by marcvanandel** [comment]
Specifieke typen van sensoren is met name een 'guideline' / begrenzing in de UI (en backend?). Wat er in het netwerk gedeeld wordt, is in beginsel niet beperkt. Dat maakt het mogelijk om nieuwe typen te ondersteunen zonder de software componenten in alle nodes van het netwerk bij te moeten werken. Dat geeft de vrijheid ... en risico van gecontroleerde 'wildgroei'.

**Comment by robhaans** [comment]
Grootste twijfel: maken we een specifieke lijst voor de meest gebruikte specifieke sensoren? Of maken we een categorie-achtige lijst? Want https://en.wikipedia.org/wiki/List_of_sensors is wel erg lang..

**Comment by marcvanandel** [comment]
Goed werk!

Zou de 2e optie niet meer bij `Device` horen dan bij `Sensor`? Zouden we daar een uitgebreidere lijst van moeten maken? En dat is dan ook gelijk het antwoord op wat we dan voor sensortype kunnen gebruiken: optie 1.

Een heel andere optie - die ik niet heel aantrekkelijk vind klinken - is optie 1 en 2 combineren. Dan kun je dus kiezen voor óf de precieze sensortype óf voor een abstractie daarvan ... 🤔 Dat geeft wel erg veel ruimte, vind je niet?

**Comment by robhaans** [comment]
Mbt je eerste punt: nee. Een device is het kastje, de sensor het functionele deel dat meet. Deze verwarring ontstaat steeds door het verschil tussen sensor als een specifiek meet-component en sensor als benaming voor het geheel, het kastje plus wat het doet (en soms zelfs waarom), wat we in het datamodel als "sensor-aggregate" hebben geduid.

**Comment by robhaans** [comment]
Mbt je tweede punt: dat zou heel mooi zijn. Alleen een uitdaging voor de UI..

**Comment by marcvanandel** [comment]
Muah, dat valt wel mee, denk ik. We zouden een gesorteerde lijst kunnen hanteren?

```
abstracte types
--- (scheidingsteken in de lijst)
veel voorkomende specifieke types
--- (scheidingsteken in de lijst)
alle specifieke types
```
En daar moet je dan wel met typen in kunnen zoeken. Dan begin je gewoon met typen van bijv. 'kli' en dan filtert te lijst automatisch - met behoud van sortering / opdeling - op types die iets met klimaat (of specifiek 'kli' in de naam) hebben. 

Zou zoiets goed werken? Dan ondersteunen we alle ca. 400 types en maken we invoeren toch gemakkelijk.

We zouden ook dat laatste deel van de lijst (eerst) weg kunnen laten, zodat we een minder grote keuze toelaten. Ik denk dat dat gemakkelijker is voor de gebruiker omdat een aantal types heel erg op elkaar lijken. Dat vraagt wel om een filtering ... die moeilijk is. Ik durf daar geen beslissing over te maken omdat ik veel te weinig kennis heb van welke sensoren er geregistreerd zouden moeten worden. Wie heeft daar wel voldoende kijk op?

**Comment by kad-bloemy** [comment]
In FAB 24/3 voorgesteld een tweetraps lijst te gebruiken: met als eerste niveau de abstracte categorieën zoals die op Wikipedia staan (zie hierboven) met daaronder per categorie een verbijzondering. Excel aan leden FAB rondgestuurd ter becommentariëring.

**Comment by marcvanandel** [comment]
Yes! Geïmplementeerd in de frontend
