### ISSUE TITLE
Datamodel: "theme" verplaatsen van sensors naar datastream en categoriseren op basis van TOP 1.1 (data.overheid.nl)

### ISSUE THREAD

**Issue by robhaans** [kadaster-labs/sensrnet-home#97]
Een functionele aanduiding van sensoren zoals deze nu in het model staan, zoals "natuur en klimaat" is heel lastig; een sensor is een technisch instrument dat voor heel veel thema's ingezet kan worden, zelfs op basis van dezelfde technische opzet. Het relateren aan onderwerpen of thema's is vooral omdat we willen weten welke waarden de sensor oplevert in de datastream. Vandaar dat we voorstellen om de entiteit "thema" te verplaatsen naar de datastream en hiervoor de thema's van TOP 1.1 van KOOP (data.overheid.nl) als basis te gebruiken: [TOP-lijst 1.1.xlsx](https://github.com/kadaster-labs/sensrnet-home/files/5603746/TOP-lijst.1.1.xlsx). 

Een subset hiervan is:
- dienstensector
- energie
- landbouw, visserij,   voedselkwaliteit
- markttoezicht
- ondernemen
- transport
- afval
- bodem
- geluid
- klimaatverandering
- lucht
- natuur- en landschapsbeheer
- stoffen
- water
- veiligheid
- informatievoorziening en ICT
- inkoop en beheer
- netwerken
- ruimtelijke ordening
- waterbeheer
- luchtvaart
- openbaar vervoer
- rail- en wegverkeer
- scheepvaart
- bouwen en verbouwen
- woningmarkt
- gezondheidsrisico's

Het voordeel van aansluiting op TOP, is dat het een bestaande standaard is die gebruikt wordt om datasets te categoriseren op data.overheid.nl. Hiermee wordt koppeling van datastreams aan data.overheid.nl makkelijker.

Meer info over de opzet van de lijst is hier te vinden: https://standaarden.overheid.nl/owms/4.0/doc/waardelijsten/thema-indeling-voor-officiele-publicaties

**Comment by robhaans** [comment]
Hiermee kunnen issues 74, 75 en 77 eigenlijk gesloten worden. Het uitbouwen van het SensrNet datamodel naar "observations", "observed properties" en "featureOfInterest" lijkt voor de MVP een brug te ver.

**Comment by marcvanandel** [comment]
We hebben vandaag (dd 2 dec 2020) besloten dat we uit gaan van deze lijst. Later (na MVP) zou vanuit `data.overheid.nl` een koppeling op deze thema's gemaakt kunnen worden.

**Comment by pvgenuchten** [comment]
ik zat vandaag toevallig naar dezelfde lijst te kijken, echter volgens mij is deze nog niet productie rijp, de gebruikte uri's in https://repository.officiele-overheidspublicaties.nl/waardelijsten/toplijst_1.1/2/json/toplijst_1.1_v2.json lijken me nog niet stabiel

**Comment by robhaans** [comment]
> ik zat vandaag toevallig naar dezelfde lijst te kijken, echter volgens mij is deze nog niet productie rijp, de gebruikte uri's in https://repository.officiele-overheidspublicaties.nl/waardelijsten/toplijst_1.1/2/json/toplijst_1.1_v2.json lijken me nog niet stabiel

Waaruit blijkt dit? Ik kan contact opnemen met KOOP (de beheerder/eigenaar) om te bepalen wat het issue is een een oplossing te vinden.

**Comment by kad-bloemy** [comment]
Lijst volgens toplijst 1.1 overgenomen.
