### ISSUE TITLE
Datamodel: nieuwe eigenschap van datastream --> "ContainsPIData"

### ISSUE THREAD

**Issue by robhaans** [kadaster-labs/sensrnet-home#98]
Een belangrijke reden voor het vastleggen van sensoren in een register is het geven van transparantie. Een van de aandachtspunten in het kader van transparantie is de basisvraag: bevat de datastream gegevens die herleidbaar zijn tot individuele personen? 

Evt. zou bij een "ja" nog extra informatie toegevoegd kunnen worden, zoals een privacystatement of een link naar een register van verwerkingen.

**Comment by kad-bloemy** [comment]
Kan deze worden gesloten of moet het nog worden doorgevoerd in de code?

**Comment by marcvanandel** [comment]
Yes! Opgenomen met #118
